## 数据集分割方法【欢迎同学们一起交流总结方法，共同进步，做大做强，有好的方法或者建议，欢迎邮件765187944@qq.com】

In [1]:
# 创建数据集
import torch
import numpy as np
from PIL import Image
from torch.utils.data import Dataset
import os
import pandas as pd

## 创建映射型数据集

In [3]:
class MyData(Dataset):
    def __init__(self, image_dir, label_dir=None, transform=None):
        super(MyData, self).__init__()
        self.image_dir = image_dir
        self.transform = transform
        if label_dir:
            self.df = pd.read_csv(label_dir)
            self.label_dict = {}
            for i, label in enumerate(self.df['label'].unique()):
                self.label_dict[label]=i
            self.reverse_label_dict = {v:k for k,v in self.label_dict.items()}
            self.df['encoded'] = self.df['label'].map(self.label_dict)
        else:
            self.df = pd.DataFrame({'image': os.listdir(self.image_dir),
                                   'label': np.zeros(len(os.listdir(self.image_dir))),
                                   'encoded': np.zeros(len(os.listdir(self.image_dir)))})
    
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, item):
        image_path = os.path.join(self.image_dir, self.df.iloc[item, 0])
        image = np.asarray(Image.open(image_path).convert('RGB'))
        label = torch.tensor(self.df.iloc[item, 2])
        if self.transform:
            image = self.transform(image)
        return image, label
        
            
    

In [4]:
train_valid_data = MyData(image_dir='E:\\Mlearning\\DL_competition\\classify leaves\\train_set', label_dir = 'E:\\Mlearning\\DL_competition\\classify leaves\\train.csv')

In [5]:
len(train_valid_data)

18353

## 分割数据集【Subset and random_split】
## subset与random_split直接针对数据集（image与label都被划分）划分

In [5]:
# Subset and np.random.shuffle
data_size = len(train_valid_data)
data_idx = list(range(data_size))
np.random.shuffle(data_idx)
valid_size = int(np.floor(data_size*0.2))
train_idx = data_idx[valid_size:]
valid_idx = data_idx[:valid_size]
train_data = torch.utils.data.Subset(train_valid_data, train_idx)
valid_data = torch.utils.data.Subset(train_valid_data, valid_idx)

In [6]:
len(train_data), len(valid_data)

(14683, 3670)

In [7]:
# torch.utils.data.random_split
train_set, valid_set = torch.utils.data.random_split(train_valid_data, lengths=[18000, 353], generator=torch.Generator().manual_seed(0))
len(train_set)

18000

##  sampler取样，取样是先划分索引，再在数据集中取对应的Image与label【与上面方法对比记忆】

In [24]:
# sampler and SubsetRandomSampler[shuffle方式采用np.random.shuffle]
train_size = len(train_valid_data)
data_idx = list(range(train_size))
np.random.seed(42)
np.random.shuffle(data_idx)
split = int(np.floor(train_size*0.2))
train_idx, valid_idx = data_idx[split:], data_idx[:split]
train_sampler = torch.utils.data.RandomSampler(train_idx)
valid_sampler = torch.utils.data.RandomSampler(valid_idx)
train_loader = torch.utils.data.DataLoader(train_valid_data, batch_size=128, sampler=train_sampler)
valid_loader = torch.utils.data.DataLoader(train_valid_data, batch_size=128, sampler=valid_sampler)

## 权重取样

In [12]:
test_data = train_valid_data
classes, counts = np.unique(test_data.df['label'], return_counts=True)
num_class = classes.shape[0]
count = counts.max()
weights = np.zeros(len(test_data))
for c in classes:
    freq_c = np.sum(test_data.df['label']==c)
    weights[test_data.df['label']==c] = len(test_data)/freq_c
weights = list(weights)
sampler = torch.utils.data.WeightedRandomSampler(weights, int(num_class*count))
len(sampler)

62128

## sklearn 数据分割方法【建议与pytorch不同目标划分对应记忆】

In [29]:
## train_test_split【针对数据集划分】
from sklearn.model_selection import train_test_split
train_set, valid_set = train_test_split(train_valid_data, test_size=0.2)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=128, shuffle=True)
len(train_loader)

115

## 交叉验证

In [31]:
## KFOLD交叉验证+sampler[SubsetRandomSampler, RandomSampler,WeightedRandomSampler]【针对索引划分后在数据集中取样】
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)
for train_idx, valid_idx in kfold.split(train_valid_data):
    print(train_idx, valid_idx)

[ 3671  3672  3673 ... 18350 18351 18352] [   0    1    2 ... 3668 3669 3670]
[    0     1     2 ... 18350 18351 18352] [3671 3672 3673 ... 7339 7340 7341]
[    0     1     2 ... 18350 18351 18352] [ 7342  7343  7344 ... 11010 11011 11012]
[    0     1     2 ... 18350 18351 18352] [11013 11014 11015 ... 14680 14681 14682]
[    0     1     2 ... 14680 14681 14682] [14683 14684 14685 ... 18350 18351 18352]


In [33]:
## RepeatedKFold+sampler[SubsetRandomSampler, RandomSampler, WeightedRandomSampler]
from sklearn.model_selection import RepeatedKFold
rkfd = RepeatedKFold(n_splits=5, n_repeats=2)
for train_idx, valid_idx in rkfd.split(train_valid_data):
    print(train_idx, valid_idx)

[    0     1     2 ... 18349 18351 18352] [    4    18    24 ... 18343 18346 18350]
[    0     1     2 ... 18349 18350 18352] [    6     8    14 ... 18338 18348 18351]
[    1     3     4 ... 18350 18351 18352] [    0     2    12 ... 18336 18347 18349]
[    0     1     2 ... 18350 18351 18352] [    3     5     7 ... 18324 18329 18344]
[    0     2     3 ... 18349 18350 18351] [    1    10    13 ... 18342 18345 18352]
[    0     1     2 ... 18349 18351 18352] [   10    14    24 ... 18332 18339 18350]
[    0     2     4 ... 18349 18350 18351] [    1     3     9 ... 18345 18348 18352]
[    1     2     3 ... 18350 18351 18352] [    0     4     7 ... 18338 18340 18349]
[    0     1     2 ... 18350 18351 18352] [    5     6    12 ... 18342 18343 18346]
[    0     1     3 ... 18349 18350 18352] [    2     8    19 ... 18333 18347 18351]


In [38]:
## leave one/p out
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
for i, (train_idx, valid_idx) in enumerate(loo.split(train_valid_data)):
    print(i, train_idx, valid_idx)

0 [    1     2     3 ... 18350 18351 18352] [0]
1 [    0     2     3 ... 18350 18351 18352] [1]
2 [    0     1     3 ... 18350 18351 18352] [2]
3 [    0     1     2 ... 18350 18351 18352] [3]
4 [    0     1     2 ... 18350 18351 18352] [4]
5 [    0     1     2 ... 18350 18351 18352] [5]
6 [    0     1     2 ... 18350 18351 18352] [6]
7 [    0     1     2 ... 18350 18351 18352] [7]
8 [    0     1     2 ... 18350 18351 18352] [8]
9 [    0     1     2 ... 18350 18351 18352] [9]
10 [    0     1     2 ... 18350 18351 18352] [10]
11 [    0     1     2 ... 18350 18351 18352] [11]
12 [    0     1     2 ... 18350 18351 18352] [12]
13 [    0     1     2 ... 18350 18351 18352] [13]
14 [    0     1     2 ... 18350 18351 18352] [14]
15 [    0     1     2 ... 18350 18351 18352] [15]
16 [    0     1     2 ... 18350 18351 18352] [16]
17 [    0     1     2 ... 18350 18351 18352] [17]
18 [    0     1     2 ... 18350 18351 18352] [18]
19 [    0     1     2 ... 18350 18351 18352] [19]
20 [    0     1     

261 [    0     1     2 ... 18350 18351 18352] [261]
262 [    0     1     2 ... 18350 18351 18352] [262]
263 [    0     1     2 ... 18350 18351 18352] [263]
264 [    0     1     2 ... 18350 18351 18352] [264]
265 [    0     1     2 ... 18350 18351 18352] [265]
266 [    0     1     2 ... 18350 18351 18352] [266]
267 [    0     1     2 ... 18350 18351 18352] [267]
268 [    0     1     2 ... 18350 18351 18352] [268]
269 [    0     1     2 ... 18350 18351 18352] [269]
270 [    0     1     2 ... 18350 18351 18352] [270]
271 [    0     1     2 ... 18350 18351 18352] [271]
272 [    0     1     2 ... 18350 18351 18352] [272]
273 [    0     1     2 ... 18350 18351 18352] [273]
274 [    0     1     2 ... 18350 18351 18352] [274]
275 [    0     1     2 ... 18350 18351 18352] [275]
276 [    0     1     2 ... 18350 18351 18352] [276]
277 [    0     1     2 ... 18350 18351 18352] [277]
278 [    0     1     2 ... 18350 18351 18352] [278]
279 [    0     1     2 ... 18350 18351 18352] [279]
280 [    0  

525 [    0     1     2 ... 18350 18351 18352] [525]
526 [    0     1     2 ... 18350 18351 18352] [526]
527 [    0     1     2 ... 18350 18351 18352] [527]
528 [    0     1     2 ... 18350 18351 18352] [528]
529 [    0     1     2 ... 18350 18351 18352] [529]
530 [    0     1     2 ... 18350 18351 18352] [530]
531 [    0     1     2 ... 18350 18351 18352] [531]
532 [    0     1     2 ... 18350 18351 18352] [532]
533 [    0     1     2 ... 18350 18351 18352] [533]
534 [    0     1     2 ... 18350 18351 18352] [534]
535 [    0     1     2 ... 18350 18351 18352] [535]
536 [    0     1     2 ... 18350 18351 18352] [536]
537 [    0     1     2 ... 18350 18351 18352] [537]
538 [    0     1     2 ... 18350 18351 18352] [538]
539 [    0     1     2 ... 18350 18351 18352] [539]
540 [    0     1     2 ... 18350 18351 18352] [540]
541 [    0     1     2 ... 18350 18351 18352] [541]
542 [    0     1     2 ... 18350 18351 18352] [542]
543 [    0     1     2 ... 18350 18351 18352] [543]
544 [    0  

785 [    0     1     2 ... 18350 18351 18352] [785]
786 [    0     1     2 ... 18350 18351 18352] [786]
787 [    0     1     2 ... 18350 18351 18352] [787]
788 [    0     1     2 ... 18350 18351 18352] [788]
789 [    0     1     2 ... 18350 18351 18352] [789]
790 [    0     1     2 ... 18350 18351 18352] [790]
791 [    0     1     2 ... 18350 18351 18352] [791]
792 [    0     1     2 ... 18350 18351 18352] [792]
793 [    0     1     2 ... 18350 18351 18352] [793]
794 [    0     1     2 ... 18350 18351 18352] [794]
795 [    0     1     2 ... 18350 18351 18352] [795]
796 [    0     1     2 ... 18350 18351 18352] [796]
797 [    0     1     2 ... 18350 18351 18352] [797]
798 [    0     1     2 ... 18350 18351 18352] [798]
799 [    0     1     2 ... 18350 18351 18352] [799]
800 [    0     1     2 ... 18350 18351 18352] [800]
801 [    0     1     2 ... 18350 18351 18352] [801]
802 [    0     1     2 ... 18350 18351 18352] [802]
803 [    0     1     2 ... 18350 18351 18352] [803]
804 [    0  

1050 [    0     1     2 ... 18350 18351 18352] [1050]
1051 [    0     1     2 ... 18350 18351 18352] [1051]
1052 [    0     1     2 ... 18350 18351 18352] [1052]
1053 [    0     1     2 ... 18350 18351 18352] [1053]
1054 [    0     1     2 ... 18350 18351 18352] [1054]
1055 [    0     1     2 ... 18350 18351 18352] [1055]
1056 [    0     1     2 ... 18350 18351 18352] [1056]
1057 [    0     1     2 ... 18350 18351 18352] [1057]
1058 [    0     1     2 ... 18350 18351 18352] [1058]
1059 [    0     1     2 ... 18350 18351 18352] [1059]
1060 [    0     1     2 ... 18350 18351 18352] [1060]
1061 [    0     1     2 ... 18350 18351 18352] [1061]
1062 [    0     1     2 ... 18350 18351 18352] [1062]
1063 [    0     1     2 ... 18350 18351 18352] [1063]
1064 [    0     1     2 ... 18350 18351 18352] [1064]
1065 [    0     1     2 ... 18350 18351 18352] [1065]
1066 [    0     1     2 ... 18350 18351 18352] [1066]
1067 [    0     1     2 ... 18350 18351 18352] [1067]
1068 [    0     1     2 ... 

1317 [    0     1     2 ... 18350 18351 18352] [1317]
1318 [    0     1     2 ... 18350 18351 18352] [1318]
1319 [    0     1     2 ... 18350 18351 18352] [1319]
1320 [    0     1     2 ... 18350 18351 18352] [1320]
1321 [    0     1     2 ... 18350 18351 18352] [1321]
1322 [    0     1     2 ... 18350 18351 18352] [1322]
1323 [    0     1     2 ... 18350 18351 18352] [1323]
1324 [    0     1     2 ... 18350 18351 18352] [1324]
1325 [    0     1     2 ... 18350 18351 18352] [1325]
1326 [    0     1     2 ... 18350 18351 18352] [1326]
1327 [    0     1     2 ... 18350 18351 18352] [1327]
1328 [    0     1     2 ... 18350 18351 18352] [1328]
1329 [    0     1     2 ... 18350 18351 18352] [1329]
1330 [    0     1     2 ... 18350 18351 18352] [1330]
1331 [    0     1     2 ... 18350 18351 18352] [1331]
1332 [    0     1     2 ... 18350 18351 18352] [1332]
1333 [    0     1     2 ... 18350 18351 18352] [1333]
1334 [    0     1     2 ... 18350 18351 18352] [1334]
1335 [    0     1     2 ... 

1573 [    0     1     2 ... 18350 18351 18352] [1573]
1574 [    0     1     2 ... 18350 18351 18352] [1574]
1575 [    0     1     2 ... 18350 18351 18352] [1575]
1576 [    0     1     2 ... 18350 18351 18352] [1576]
1577 [    0     1     2 ... 18350 18351 18352] [1577]
1578 [    0     1     2 ... 18350 18351 18352] [1578]
1579 [    0     1     2 ... 18350 18351 18352] [1579]
1580 [    0     1     2 ... 18350 18351 18352] [1580]
1581 [    0     1     2 ... 18350 18351 18352] [1581]
1582 [    0     1     2 ... 18350 18351 18352] [1582]
1583 [    0     1     2 ... 18350 18351 18352] [1583]
1584 [    0     1     2 ... 18350 18351 18352] [1584]
1585 [    0     1     2 ... 18350 18351 18352] [1585]
1586 [    0     1     2 ... 18350 18351 18352] [1586]
1587 [    0     1     2 ... 18350 18351 18352] [1587]
1588 [    0     1     2 ... 18350 18351 18352] [1588]
1589 [    0     1     2 ... 18350 18351 18352] [1589]
1590 [    0     1     2 ... 18350 18351 18352] [1590]
1591 [    0     1     2 ... 

1832 [    0     1     2 ... 18350 18351 18352] [1832]
1833 [    0     1     2 ... 18350 18351 18352] [1833]
1834 [    0     1     2 ... 18350 18351 18352] [1834]
1835 [    0     1     2 ... 18350 18351 18352] [1835]
1836 [    0     1     2 ... 18350 18351 18352] [1836]
1837 [    0     1     2 ... 18350 18351 18352] [1837]
1838 [    0     1     2 ... 18350 18351 18352] [1838]
1839 [    0     1     2 ... 18350 18351 18352] [1839]
1840 [    0     1     2 ... 18350 18351 18352] [1840]
1841 [    0     1     2 ... 18350 18351 18352] [1841]
1842 [    0     1     2 ... 18350 18351 18352] [1842]
1843 [    0     1     2 ... 18350 18351 18352] [1843]
1844 [    0     1     2 ... 18350 18351 18352] [1844]
1845 [    0     1     2 ... 18350 18351 18352] [1845]
1846 [    0     1     2 ... 18350 18351 18352] [1846]
1847 [    0     1     2 ... 18350 18351 18352] [1847]
1848 [    0     1     2 ... 18350 18351 18352] [1848]
1849 [    0     1     2 ... 18350 18351 18352] [1849]
1850 [    0     1     2 ... 

2054 [    0     1     2 ... 18350 18351 18352] [2054]
2055 [    0     1     2 ... 18350 18351 18352] [2055]
2056 [    0     1     2 ... 18350 18351 18352] [2056]
2057 [    0     1     2 ... 18350 18351 18352] [2057]
2058 [    0     1     2 ... 18350 18351 18352] [2058]
2059 [    0     1     2 ... 18350 18351 18352] [2059]
2060 [    0     1     2 ... 18350 18351 18352] [2060]
2061 [    0     1     2 ... 18350 18351 18352] [2061]
2062 [    0     1     2 ... 18350 18351 18352] [2062]
2063 [    0     1     2 ... 18350 18351 18352] [2063]
2064 [    0     1     2 ... 18350 18351 18352] [2064]
2065 [    0     1     2 ... 18350 18351 18352] [2065]
2066 [    0     1     2 ... 18350 18351 18352] [2066]
2067 [    0     1     2 ... 18350 18351 18352] [2067]
2068 [    0     1     2 ... 18350 18351 18352] [2068]
2069 [    0     1     2 ... 18350 18351 18352] [2069]
2070 [    0     1     2 ... 18350 18351 18352] [2070]
2071 [    0     1     2 ... 18350 18351 18352] [2071]
2072 [    0     1     2 ... 

2286 [    0     1     2 ... 18350 18351 18352] [2286]
2287 [    0     1     2 ... 18350 18351 18352] [2287]
2288 [    0     1     2 ... 18350 18351 18352] [2288]
2289 [    0     1     2 ... 18350 18351 18352] [2289]
2290 [    0     1     2 ... 18350 18351 18352] [2290]
2291 [    0     1     2 ... 18350 18351 18352] [2291]
2292 [    0     1     2 ... 18350 18351 18352] [2292]
2293 [    0     1     2 ... 18350 18351 18352] [2293]
2294 [    0     1     2 ... 18350 18351 18352] [2294]
2295 [    0     1     2 ... 18350 18351 18352] [2295]
2296 [    0     1     2 ... 18350 18351 18352] [2296]
2297 [    0     1     2 ... 18350 18351 18352] [2297]
2298 [    0     1     2 ... 18350 18351 18352] [2298]
2299 [    0     1     2 ... 18350 18351 18352] [2299]
2300 [    0     1     2 ... 18350 18351 18352] [2300]
2301 [    0     1     2 ... 18350 18351 18352] [2301]
2302 [    0     1     2 ... 18350 18351 18352] [2302]
2303 [    0     1     2 ... 18350 18351 18352] [2303]
2304 [    0     1     2 ... 

2549 [    0     1     2 ... 18350 18351 18352] [2549]
2550 [    0     1     2 ... 18350 18351 18352] [2550]
2551 [    0     1     2 ... 18350 18351 18352] [2551]
2552 [    0     1     2 ... 18350 18351 18352] [2552]
2553 [    0     1     2 ... 18350 18351 18352] [2553]
2554 [    0     1     2 ... 18350 18351 18352] [2554]
2555 [    0     1     2 ... 18350 18351 18352] [2555]
2556 [    0     1     2 ... 18350 18351 18352] [2556]
2557 [    0     1     2 ... 18350 18351 18352] [2557]
2558 [    0     1     2 ... 18350 18351 18352] [2558]
2559 [    0     1     2 ... 18350 18351 18352] [2559]
2560 [    0     1     2 ... 18350 18351 18352] [2560]
2561 [    0     1     2 ... 18350 18351 18352] [2561]
2562 [    0     1     2 ... 18350 18351 18352] [2562]
2563 [    0     1     2 ... 18350 18351 18352] [2563]
2564 [    0     1     2 ... 18350 18351 18352] [2564]
2565 [    0     1     2 ... 18350 18351 18352] [2565]
2566 [    0     1     2 ... 18350 18351 18352] [2566]
2567 [    0     1     2 ... 

2816 [    0     1     2 ... 18350 18351 18352] [2816]
2817 [    0     1     2 ... 18350 18351 18352] [2817]
2818 [    0     1     2 ... 18350 18351 18352] [2818]
2819 [    0     1     2 ... 18350 18351 18352] [2819]
2820 [    0     1     2 ... 18350 18351 18352] [2820]
2821 [    0     1     2 ... 18350 18351 18352] [2821]
2822 [    0     1     2 ... 18350 18351 18352] [2822]
2823 [    0     1     2 ... 18350 18351 18352] [2823]
2824 [    0     1     2 ... 18350 18351 18352] [2824]
2825 [    0     1     2 ... 18350 18351 18352] [2825]
2826 [    0     1     2 ... 18350 18351 18352] [2826]
2827 [    0     1     2 ... 18350 18351 18352] [2827]
2828 [    0     1     2 ... 18350 18351 18352] [2828]
2829 [    0     1     2 ... 18350 18351 18352] [2829]
2830 [    0     1     2 ... 18350 18351 18352] [2830]
2831 [    0     1     2 ... 18350 18351 18352] [2831]
2832 [    0     1     2 ... 18350 18351 18352] [2832]
2833 [    0     1     2 ... 18350 18351 18352] [2833]
2834 [    0     1     2 ... 

3084 [    0     1     2 ... 18350 18351 18352] [3084]
3085 [    0     1     2 ... 18350 18351 18352] [3085]
3086 [    0     1     2 ... 18350 18351 18352] [3086]
3087 [    0     1     2 ... 18350 18351 18352] [3087]
3088 [    0     1     2 ... 18350 18351 18352] [3088]
3089 [    0     1     2 ... 18350 18351 18352] [3089]
3090 [    0     1     2 ... 18350 18351 18352] [3090]
3091 [    0     1     2 ... 18350 18351 18352] [3091]
3092 [    0     1     2 ... 18350 18351 18352] [3092]
3093 [    0     1     2 ... 18350 18351 18352] [3093]
3094 [    0     1     2 ... 18350 18351 18352] [3094]
3095 [    0     1     2 ... 18350 18351 18352] [3095]
3096 [    0     1     2 ... 18350 18351 18352] [3096]
3097 [    0     1     2 ... 18350 18351 18352] [3097]
3098 [    0     1     2 ... 18350 18351 18352] [3098]
3099 [    0     1     2 ... 18350 18351 18352] [3099]
3100 [    0     1     2 ... 18350 18351 18352] [3100]
3101 [    0     1     2 ... 18350 18351 18352] [3101]
3102 [    0     1     2 ... 

3317 [    0     1     2 ... 18350 18351 18352] [3317]
3318 [    0     1     2 ... 18350 18351 18352] [3318]
3319 [    0     1     2 ... 18350 18351 18352] [3319]
3320 [    0     1     2 ... 18350 18351 18352] [3320]
3321 [    0     1     2 ... 18350 18351 18352] [3321]
3322 [    0     1     2 ... 18350 18351 18352] [3322]
3323 [    0     1     2 ... 18350 18351 18352] [3323]
3324 [    0     1     2 ... 18350 18351 18352] [3324]
3325 [    0     1     2 ... 18350 18351 18352] [3325]
3326 [    0     1     2 ... 18350 18351 18352] [3326]
3327 [    0     1     2 ... 18350 18351 18352] [3327]
3328 [    0     1     2 ... 18350 18351 18352] [3328]
3329 [    0     1     2 ... 18350 18351 18352] [3329]
3330 [    0     1     2 ... 18350 18351 18352] [3330]
3331 [    0     1     2 ... 18350 18351 18352] [3331]
3332 [    0     1     2 ... 18350 18351 18352] [3332]
3333 [    0     1     2 ... 18350 18351 18352] [3333]
3334 [    0     1     2 ... 18350 18351 18352] [3334]
3335 [    0     1     2 ... 

3567 [    0     1     2 ... 18350 18351 18352] [3567]
3568 [    0     1     2 ... 18350 18351 18352] [3568]
3569 [    0     1     2 ... 18350 18351 18352] [3569]
3570 [    0     1     2 ... 18350 18351 18352] [3570]
3571 [    0     1     2 ... 18350 18351 18352] [3571]
3572 [    0     1     2 ... 18350 18351 18352] [3572]
3573 [    0     1     2 ... 18350 18351 18352] [3573]
3574 [    0     1     2 ... 18350 18351 18352] [3574]
3575 [    0     1     2 ... 18350 18351 18352] [3575]
3576 [    0     1     2 ... 18350 18351 18352] [3576]
3577 [    0     1     2 ... 18350 18351 18352] [3577]
3578 [    0     1     2 ... 18350 18351 18352] [3578]
3579 [    0     1     2 ... 18350 18351 18352] [3579]
3580 [    0     1     2 ... 18350 18351 18352] [3580]
3581 [    0     1     2 ... 18350 18351 18352] [3581]
3582 [    0     1     2 ... 18350 18351 18352] [3582]
3583 [    0     1     2 ... 18350 18351 18352] [3583]
3584 [    0     1     2 ... 18350 18351 18352] [3584]
3585 [    0     1     2 ... 

3800 [    0     1     2 ... 18350 18351 18352] [3800]
3801 [    0     1     2 ... 18350 18351 18352] [3801]
3802 [    0     1     2 ... 18350 18351 18352] [3802]
3803 [    0     1     2 ... 18350 18351 18352] [3803]
3804 [    0     1     2 ... 18350 18351 18352] [3804]
3805 [    0     1     2 ... 18350 18351 18352] [3805]
3806 [    0     1     2 ... 18350 18351 18352] [3806]
3807 [    0     1     2 ... 18350 18351 18352] [3807]
3808 [    0     1     2 ... 18350 18351 18352] [3808]
3809 [    0     1     2 ... 18350 18351 18352] [3809]
3810 [    0     1     2 ... 18350 18351 18352] [3810]
3811 [    0     1     2 ... 18350 18351 18352] [3811]
3812 [    0     1     2 ... 18350 18351 18352] [3812]
3813 [    0     1     2 ... 18350 18351 18352] [3813]
3814 [    0     1     2 ... 18350 18351 18352] [3814]
3815 [    0     1     2 ... 18350 18351 18352] [3815]
3816 [    0     1     2 ... 18350 18351 18352] [3816]
3817 [    0     1     2 ... 18350 18351 18352] [3817]
3818 [    0     1     2 ... 

4063 [    0     1     2 ... 18350 18351 18352] [4063]
4064 [    0     1     2 ... 18350 18351 18352] [4064]
4065 [    0     1     2 ... 18350 18351 18352] [4065]
4066 [    0     1     2 ... 18350 18351 18352] [4066]
4067 [    0     1     2 ... 18350 18351 18352] [4067]
4068 [    0     1     2 ... 18350 18351 18352] [4068]
4069 [    0     1     2 ... 18350 18351 18352] [4069]
4070 [    0     1     2 ... 18350 18351 18352] [4070]
4071 [    0     1     2 ... 18350 18351 18352] [4071]
4072 [    0     1     2 ... 18350 18351 18352] [4072]
4073 [    0     1     2 ... 18350 18351 18352] [4073]
4074 [    0     1     2 ... 18350 18351 18352] [4074]
4075 [    0     1     2 ... 18350 18351 18352] [4075]
4076 [    0     1     2 ... 18350 18351 18352] [4076]
4077 [    0     1     2 ... 18350 18351 18352] [4077]
4078 [    0     1     2 ... 18350 18351 18352] [4078]
4079 [    0     1     2 ... 18350 18351 18352] [4079]
4080 [    0     1     2 ... 18350 18351 18352] [4080]
4081 [    0     1     2 ... 

4329 [    0     1     2 ... 18350 18351 18352] [4329]
4330 [    0     1     2 ... 18350 18351 18352] [4330]
4331 [    0     1     2 ... 18350 18351 18352] [4331]
4332 [    0     1     2 ... 18350 18351 18352] [4332]
4333 [    0     1     2 ... 18350 18351 18352] [4333]
4334 [    0     1     2 ... 18350 18351 18352] [4334]
4335 [    0     1     2 ... 18350 18351 18352] [4335]
4336 [    0     1     2 ... 18350 18351 18352] [4336]
4337 [    0     1     2 ... 18350 18351 18352] [4337]
4338 [    0     1     2 ... 18350 18351 18352] [4338]
4339 [    0     1     2 ... 18350 18351 18352] [4339]
4340 [    0     1     2 ... 18350 18351 18352] [4340]
4341 [    0     1     2 ... 18350 18351 18352] [4341]
4342 [    0     1     2 ... 18350 18351 18352] [4342]
4343 [    0     1     2 ... 18350 18351 18352] [4343]
4344 [    0     1     2 ... 18350 18351 18352] [4344]
4345 [    0     1     2 ... 18350 18351 18352] [4345]
4346 [    0     1     2 ... 18350 18351 18352] [4346]
4347 [    0     1     2 ... 

4596 [    0     1     2 ... 18350 18351 18352] [4596]
4597 [    0     1     2 ... 18350 18351 18352] [4597]
4598 [    0     1     2 ... 18350 18351 18352] [4598]
4599 [    0     1     2 ... 18350 18351 18352] [4599]
4600 [    0     1     2 ... 18350 18351 18352] [4600]
4601 [    0     1     2 ... 18350 18351 18352] [4601]
4602 [    0     1     2 ... 18350 18351 18352] [4602]
4603 [    0     1     2 ... 18350 18351 18352] [4603]
4604 [    0     1     2 ... 18350 18351 18352] [4604]
4605 [    0     1     2 ... 18350 18351 18352] [4605]
4606 [    0     1     2 ... 18350 18351 18352] [4606]
4607 [    0     1     2 ... 18350 18351 18352] [4607]
4608 [    0     1     2 ... 18350 18351 18352] [4608]
4609 [    0     1     2 ... 18350 18351 18352] [4609]
4610 [    0     1     2 ... 18350 18351 18352] [4610]
4611 [    0     1     2 ... 18350 18351 18352] [4611]
4612 [    0     1     2 ... 18350 18351 18352] [4612]
4613 [    0     1     2 ... 18350 18351 18352] [4613]
4614 [    0     1     2 ... 

4861 [    0     1     2 ... 18350 18351 18352] [4861]
4862 [    0     1     2 ... 18350 18351 18352] [4862]
4863 [    0     1     2 ... 18350 18351 18352] [4863]
4864 [    0     1     2 ... 18350 18351 18352] [4864]
4865 [    0     1     2 ... 18350 18351 18352] [4865]
4866 [    0     1     2 ... 18350 18351 18352] [4866]
4867 [    0     1     2 ... 18350 18351 18352] [4867]
4868 [    0     1     2 ... 18350 18351 18352] [4868]
4869 [    0     1     2 ... 18350 18351 18352] [4869]
4870 [    0     1     2 ... 18350 18351 18352] [4870]
4871 [    0     1     2 ... 18350 18351 18352] [4871]
4872 [    0     1     2 ... 18350 18351 18352] [4872]
4873 [    0     1     2 ... 18350 18351 18352] [4873]
4874 [    0     1     2 ... 18350 18351 18352] [4874]
4875 [    0     1     2 ... 18350 18351 18352] [4875]
4876 [    0     1     2 ... 18350 18351 18352] [4876]
4877 [    0     1     2 ... 18350 18351 18352] [4877]
4878 [    0     1     2 ... 18350 18351 18352] [4878]
4879 [    0     1     2 ... 

5118 [    0     1     2 ... 18350 18351 18352] [5118]
5119 [    0     1     2 ... 18350 18351 18352] [5119]
5120 [    0     1     2 ... 18350 18351 18352] [5120]
5121 [    0     1     2 ... 18350 18351 18352] [5121]
5122 [    0     1     2 ... 18350 18351 18352] [5122]
5123 [    0     1     2 ... 18350 18351 18352] [5123]
5124 [    0     1     2 ... 18350 18351 18352] [5124]
5125 [    0     1     2 ... 18350 18351 18352] [5125]
5126 [    0     1     2 ... 18350 18351 18352] [5126]
5127 [    0     1     2 ... 18350 18351 18352] [5127]
5128 [    0     1     2 ... 18350 18351 18352] [5128]
5129 [    0     1     2 ... 18350 18351 18352] [5129]
5130 [    0     1     2 ... 18350 18351 18352] [5130]
5131 [    0     1     2 ... 18350 18351 18352] [5131]
5132 [    0     1     2 ... 18350 18351 18352] [5132]
5133 [    0     1     2 ... 18350 18351 18352] [5133]
5134 [    0     1     2 ... 18350 18351 18352] [5134]
5135 [    0     1     2 ... 18350 18351 18352] [5135]
5136 [    0     1     2 ... 

5353 [    0     1     2 ... 18350 18351 18352] [5353]
5354 [    0     1     2 ... 18350 18351 18352] [5354]
5355 [    0     1     2 ... 18350 18351 18352] [5355]
5356 [    0     1     2 ... 18350 18351 18352] [5356]
5357 [    0     1     2 ... 18350 18351 18352] [5357]
5358 [    0     1     2 ... 18350 18351 18352] [5358]
5359 [    0     1     2 ... 18350 18351 18352] [5359]
5360 [    0     1     2 ... 18350 18351 18352] [5360]
5361 [    0     1     2 ... 18350 18351 18352] [5361]
5362 [    0     1     2 ... 18350 18351 18352] [5362]
5363 [    0     1     2 ... 18350 18351 18352] [5363]
5364 [    0     1     2 ... 18350 18351 18352] [5364]
5365 [    0     1     2 ... 18350 18351 18352] [5365]
5366 [    0     1     2 ... 18350 18351 18352] [5366]
5367 [    0     1     2 ... 18350 18351 18352] [5367]
5368 [    0     1     2 ... 18350 18351 18352] [5368]
5369 [    0     1     2 ... 18350 18351 18352] [5369]
5370 [    0     1     2 ... 18350 18351 18352] [5370]
5371 [    0     1     2 ... 

5616 [    0     1     2 ... 18350 18351 18352] [5616]
5617 [    0     1     2 ... 18350 18351 18352] [5617]
5618 [    0     1     2 ... 18350 18351 18352] [5618]
5619 [    0     1     2 ... 18350 18351 18352] [5619]
5620 [    0     1     2 ... 18350 18351 18352] [5620]
5621 [    0     1     2 ... 18350 18351 18352] [5621]
5622 [    0     1     2 ... 18350 18351 18352] [5622]
5623 [    0     1     2 ... 18350 18351 18352] [5623]
5624 [    0     1     2 ... 18350 18351 18352] [5624]
5625 [    0     1     2 ... 18350 18351 18352] [5625]
5626 [    0     1     2 ... 18350 18351 18352] [5626]
5627 [    0     1     2 ... 18350 18351 18352] [5627]
5628 [    0     1     2 ... 18350 18351 18352] [5628]
5629 [    0     1     2 ... 18350 18351 18352] [5629]
5630 [    0     1     2 ... 18350 18351 18352] [5630]
5631 [    0     1     2 ... 18350 18351 18352] [5631]
5632 [    0     1     2 ... 18350 18351 18352] [5632]
5633 [    0     1     2 ... 18350 18351 18352] [5633]
5634 [    0     1     2 ... 

5849 [    0     1     2 ... 18350 18351 18352] [5849]
5850 [    0     1     2 ... 18350 18351 18352] [5850]
5851 [    0     1     2 ... 18350 18351 18352] [5851]
5852 [    0     1     2 ... 18350 18351 18352] [5852]
5853 [    0     1     2 ... 18350 18351 18352] [5853]
5854 [    0     1     2 ... 18350 18351 18352] [5854]
5855 [    0     1     2 ... 18350 18351 18352] [5855]
5856 [    0     1     2 ... 18350 18351 18352] [5856]
5857 [    0     1     2 ... 18350 18351 18352] [5857]
5858 [    0     1     2 ... 18350 18351 18352] [5858]
5859 [    0     1     2 ... 18350 18351 18352] [5859]
5860 [    0     1     2 ... 18350 18351 18352] [5860]
5861 [    0     1     2 ... 18350 18351 18352] [5861]
5862 [    0     1     2 ... 18350 18351 18352] [5862]
5863 [    0     1     2 ... 18350 18351 18352] [5863]
5864 [    0     1     2 ... 18350 18351 18352] [5864]
5865 [    0     1     2 ... 18350 18351 18352] [5865]
5866 [    0     1     2 ... 18350 18351 18352] [5866]
5867 [    0     1     2 ... 

6113 [    0     1     2 ... 18350 18351 18352] [6113]
6114 [    0     1     2 ... 18350 18351 18352] [6114]
6115 [    0     1     2 ... 18350 18351 18352] [6115]
6116 [    0     1     2 ... 18350 18351 18352] [6116]
6117 [    0     1     2 ... 18350 18351 18352] [6117]
6118 [    0     1     2 ... 18350 18351 18352] [6118]
6119 [    0     1     2 ... 18350 18351 18352] [6119]
6120 [    0     1     2 ... 18350 18351 18352] [6120]
6121 [    0     1     2 ... 18350 18351 18352] [6121]
6122 [    0     1     2 ... 18350 18351 18352] [6122]
6123 [    0     1     2 ... 18350 18351 18352] [6123]
6124 [    0     1     2 ... 18350 18351 18352] [6124]
6125 [    0     1     2 ... 18350 18351 18352] [6125]
6126 [    0     1     2 ... 18350 18351 18352] [6126]
6127 [    0     1     2 ... 18350 18351 18352] [6127]
6128 [    0     1     2 ... 18350 18351 18352] [6128]
6129 [    0     1     2 ... 18350 18351 18352] [6129]
6130 [    0     1     2 ... 18350 18351 18352] [6130]
6131 [    0     1     2 ... 

6352 [    0     1     2 ... 18350 18351 18352] [6352]
6353 [    0     1     2 ... 18350 18351 18352] [6353]
6354 [    0     1     2 ... 18350 18351 18352] [6354]
6355 [    0     1     2 ... 18350 18351 18352] [6355]
6356 [    0     1     2 ... 18350 18351 18352] [6356]
6357 [    0     1     2 ... 18350 18351 18352] [6357]
6358 [    0     1     2 ... 18350 18351 18352] [6358]
6359 [    0     1     2 ... 18350 18351 18352] [6359]
6360 [    0     1     2 ... 18350 18351 18352] [6360]
6361 [    0     1     2 ... 18350 18351 18352] [6361]
6362 [    0     1     2 ... 18350 18351 18352] [6362]
6363 [    0     1     2 ... 18350 18351 18352] [6363]
6364 [    0     1     2 ... 18350 18351 18352] [6364]
6365 [    0     1     2 ... 18350 18351 18352] [6365]
6366 [    0     1     2 ... 18350 18351 18352] [6366]
6367 [    0     1     2 ... 18350 18351 18352] [6367]
6368 [    0     1     2 ... 18350 18351 18352] [6368]
6369 [    0     1     2 ... 18350 18351 18352] [6369]
6370 [    0     1     2 ... 

6607 [    0     1     2 ... 18350 18351 18352] [6607]
6608 [    0     1     2 ... 18350 18351 18352] [6608]
6609 [    0     1     2 ... 18350 18351 18352] [6609]
6610 [    0     1     2 ... 18350 18351 18352] [6610]
6611 [    0     1     2 ... 18350 18351 18352] [6611]
6612 [    0     1     2 ... 18350 18351 18352] [6612]
6613 [    0     1     2 ... 18350 18351 18352] [6613]
6614 [    0     1     2 ... 18350 18351 18352] [6614]
6615 [    0     1     2 ... 18350 18351 18352] [6615]
6616 [    0     1     2 ... 18350 18351 18352] [6616]
6617 [    0     1     2 ... 18350 18351 18352] [6617]
6618 [    0     1     2 ... 18350 18351 18352] [6618]
6619 [    0     1     2 ... 18350 18351 18352] [6619]
6620 [    0     1     2 ... 18350 18351 18352] [6620]
6621 [    0     1     2 ... 18350 18351 18352] [6621]
6622 [    0     1     2 ... 18350 18351 18352] [6622]
6623 [    0     1     2 ... 18350 18351 18352] [6623]
6624 [    0     1     2 ... 18350 18351 18352] [6624]
6625 [    0     1     2 ... 

6841 [    0     1     2 ... 18350 18351 18352] [6841]
6842 [    0     1     2 ... 18350 18351 18352] [6842]
6843 [    0     1     2 ... 18350 18351 18352] [6843]
6844 [    0     1     2 ... 18350 18351 18352] [6844]
6845 [    0     1     2 ... 18350 18351 18352] [6845]
6846 [    0     1     2 ... 18350 18351 18352] [6846]
6847 [    0     1     2 ... 18350 18351 18352] [6847]
6848 [    0     1     2 ... 18350 18351 18352] [6848]
6849 [    0     1     2 ... 18350 18351 18352] [6849]
6850 [    0     1     2 ... 18350 18351 18352] [6850]
6851 [    0     1     2 ... 18350 18351 18352] [6851]
6852 [    0     1     2 ... 18350 18351 18352] [6852]
6853 [    0     1     2 ... 18350 18351 18352] [6853]
6854 [    0     1     2 ... 18350 18351 18352] [6854]
6855 [    0     1     2 ... 18350 18351 18352] [6855]
6856 [    0     1     2 ... 18350 18351 18352] [6856]
6857 [    0     1     2 ... 18350 18351 18352] [6857]
6858 [    0     1     2 ... 18350 18351 18352] [6858]
6859 [    0     1     2 ... 

7103 [    0     1     2 ... 18350 18351 18352] [7103]
7104 [    0     1     2 ... 18350 18351 18352] [7104]
7105 [    0     1     2 ... 18350 18351 18352] [7105]
7106 [    0     1     2 ... 18350 18351 18352] [7106]
7107 [    0     1     2 ... 18350 18351 18352] [7107]
7108 [    0     1     2 ... 18350 18351 18352] [7108]
7109 [    0     1     2 ... 18350 18351 18352] [7109]
7110 [    0     1     2 ... 18350 18351 18352] [7110]
7111 [    0     1     2 ... 18350 18351 18352] [7111]
7112 [    0     1     2 ... 18350 18351 18352] [7112]
7113 [    0     1     2 ... 18350 18351 18352] [7113]
7114 [    0     1     2 ... 18350 18351 18352] [7114]
7115 [    0     1     2 ... 18350 18351 18352] [7115]
7116 [    0     1     2 ... 18350 18351 18352] [7116]
7117 [    0     1     2 ... 18350 18351 18352] [7117]
7118 [    0     1     2 ... 18350 18351 18352] [7118]
7119 [    0     1     2 ... 18350 18351 18352] [7119]
7120 [    0     1     2 ... 18350 18351 18352] [7120]
7121 [    0     1     2 ... 

7360 [    0     1     2 ... 18350 18351 18352] [7360]
7361 [    0     1     2 ... 18350 18351 18352] [7361]
7362 [    0     1     2 ... 18350 18351 18352] [7362]
7363 [    0     1     2 ... 18350 18351 18352] [7363]
7364 [    0     1     2 ... 18350 18351 18352] [7364]
7365 [    0     1     2 ... 18350 18351 18352] [7365]
7366 [    0     1     2 ... 18350 18351 18352] [7366]
7367 [    0     1     2 ... 18350 18351 18352] [7367]
7368 [    0     1     2 ... 18350 18351 18352] [7368]
7369 [    0     1     2 ... 18350 18351 18352] [7369]
7370 [    0     1     2 ... 18350 18351 18352] [7370]
7371 [    0     1     2 ... 18350 18351 18352] [7371]
7372 [    0     1     2 ... 18350 18351 18352] [7372]
7373 [    0     1     2 ... 18350 18351 18352] [7373]
7374 [    0     1     2 ... 18350 18351 18352] [7374]
7375 [    0     1     2 ... 18350 18351 18352] [7375]
7376 [    0     1     2 ... 18350 18351 18352] [7376]
7377 [    0     1     2 ... 18350 18351 18352] [7377]
7378 [    0     1     2 ... 

7598 [    0     1     2 ... 18350 18351 18352] [7598]
7599 [    0     1     2 ... 18350 18351 18352] [7599]
7600 [    0     1     2 ... 18350 18351 18352] [7600]
7601 [    0     1     2 ... 18350 18351 18352] [7601]
7602 [    0     1     2 ... 18350 18351 18352] [7602]
7603 [    0     1     2 ... 18350 18351 18352] [7603]
7604 [    0     1     2 ... 18350 18351 18352] [7604]
7605 [    0     1     2 ... 18350 18351 18352] [7605]
7606 [    0     1     2 ... 18350 18351 18352] [7606]
7607 [    0     1     2 ... 18350 18351 18352] [7607]
7608 [    0     1     2 ... 18350 18351 18352] [7608]
7609 [    0     1     2 ... 18350 18351 18352] [7609]
7610 [    0     1     2 ... 18350 18351 18352] [7610]
7611 [    0     1     2 ... 18350 18351 18352] [7611]
7612 [    0     1     2 ... 18350 18351 18352] [7612]
7613 [    0     1     2 ... 18350 18351 18352] [7613]
7614 [    0     1     2 ... 18350 18351 18352] [7614]
7615 [    0     1     2 ... 18350 18351 18352] [7615]
7616 [    0     1     2 ... 

7842 [    0     1     2 ... 18350 18351 18352] [7842]
7843 [    0     1     2 ... 18350 18351 18352] [7843]
7844 [    0     1     2 ... 18350 18351 18352] [7844]
7845 [    0     1     2 ... 18350 18351 18352] [7845]
7846 [    0     1     2 ... 18350 18351 18352] [7846]
7847 [    0     1     2 ... 18350 18351 18352] [7847]
7848 [    0     1     2 ... 18350 18351 18352] [7848]
7849 [    0     1     2 ... 18350 18351 18352] [7849]
7850 [    0     1     2 ... 18350 18351 18352] [7850]
7851 [    0     1     2 ... 18350 18351 18352] [7851]
7852 [    0     1     2 ... 18350 18351 18352] [7852]
7853 [    0     1     2 ... 18350 18351 18352] [7853]
7854 [    0     1     2 ... 18350 18351 18352] [7854]
7855 [    0     1     2 ... 18350 18351 18352] [7855]
7856 [    0     1     2 ... 18350 18351 18352] [7856]
7857 [    0     1     2 ... 18350 18351 18352] [7857]
7858 [    0     1     2 ... 18350 18351 18352] [7858]
7859 [    0     1     2 ... 18350 18351 18352] [7859]
7860 [    0     1     2 ... 

8095 [    0     1     2 ... 18350 18351 18352] [8095]
8096 [    0     1     2 ... 18350 18351 18352] [8096]
8097 [    0     1     2 ... 18350 18351 18352] [8097]
8098 [    0     1     2 ... 18350 18351 18352] [8098]
8099 [    0     1     2 ... 18350 18351 18352] [8099]
8100 [    0     1     2 ... 18350 18351 18352] [8100]
8101 [    0     1     2 ... 18350 18351 18352] [8101]
8102 [    0     1     2 ... 18350 18351 18352] [8102]
8103 [    0     1     2 ... 18350 18351 18352] [8103]
8104 [    0     1     2 ... 18350 18351 18352] [8104]
8105 [    0     1     2 ... 18350 18351 18352] [8105]
8106 [    0     1     2 ... 18350 18351 18352] [8106]
8107 [    0     1     2 ... 18350 18351 18352] [8107]
8108 [    0     1     2 ... 18350 18351 18352] [8108]
8109 [    0     1     2 ... 18350 18351 18352] [8109]
8110 [    0     1     2 ... 18350 18351 18352] [8110]
8111 [    0     1     2 ... 18350 18351 18352] [8111]
8112 [    0     1     2 ... 18350 18351 18352] [8112]
8113 [    0     1     2 ... 

8350 [    0     1     2 ... 18350 18351 18352] [8350]
8351 [    0     1     2 ... 18350 18351 18352] [8351]
8352 [    0     1     2 ... 18350 18351 18352] [8352]
8353 [    0     1     2 ... 18350 18351 18352] [8353]
8354 [    0     1     2 ... 18350 18351 18352] [8354]
8355 [    0     1     2 ... 18350 18351 18352] [8355]
8356 [    0     1     2 ... 18350 18351 18352] [8356]
8357 [    0     1     2 ... 18350 18351 18352] [8357]
8358 [    0     1     2 ... 18350 18351 18352] [8358]
8359 [    0     1     2 ... 18350 18351 18352] [8359]
8360 [    0     1     2 ... 18350 18351 18352] [8360]
8361 [    0     1     2 ... 18350 18351 18352] [8361]
8362 [    0     1     2 ... 18350 18351 18352] [8362]
8363 [    0     1     2 ... 18350 18351 18352] [8363]
8364 [    0     1     2 ... 18350 18351 18352] [8364]
8365 [    0     1     2 ... 18350 18351 18352] [8365]
8366 [    0     1     2 ... 18350 18351 18352] [8366]
8367 [    0     1     2 ... 18350 18351 18352] [8367]
8368 [    0     1     2 ... 

8590 [    0     1     2 ... 18350 18351 18352] [8590]
8591 [    0     1     2 ... 18350 18351 18352] [8591]
8592 [    0     1     2 ... 18350 18351 18352] [8592]
8593 [    0     1     2 ... 18350 18351 18352] [8593]
8594 [    0     1     2 ... 18350 18351 18352] [8594]
8595 [    0     1     2 ... 18350 18351 18352] [8595]
8596 [    0     1     2 ... 18350 18351 18352] [8596]
8597 [    0     1     2 ... 18350 18351 18352] [8597]
8598 [    0     1     2 ... 18350 18351 18352] [8598]
8599 [    0     1     2 ... 18350 18351 18352] [8599]
8600 [    0     1     2 ... 18350 18351 18352] [8600]
8601 [    0     1     2 ... 18350 18351 18352] [8601]
8602 [    0     1     2 ... 18350 18351 18352] [8602]
8603 [    0     1     2 ... 18350 18351 18352] [8603]
8604 [    0     1     2 ... 18350 18351 18352] [8604]
8605 [    0     1     2 ... 18350 18351 18352] [8605]
8606 [    0     1     2 ... 18350 18351 18352] [8606]
8607 [    0     1     2 ... 18350 18351 18352] [8607]
8608 [    0     1     2 ... 

8851 [    0     1     2 ... 18350 18351 18352] [8851]
8852 [    0     1     2 ... 18350 18351 18352] [8852]
8853 [    0     1     2 ... 18350 18351 18352] [8853]
8854 [    0     1     2 ... 18350 18351 18352] [8854]
8855 [    0     1     2 ... 18350 18351 18352] [8855]
8856 [    0     1     2 ... 18350 18351 18352] [8856]
8857 [    0     1     2 ... 18350 18351 18352] [8857]
8858 [    0     1     2 ... 18350 18351 18352] [8858]
8859 [    0     1     2 ... 18350 18351 18352] [8859]
8860 [    0     1     2 ... 18350 18351 18352] [8860]
8861 [    0     1     2 ... 18350 18351 18352] [8861]
8862 [    0     1     2 ... 18350 18351 18352] [8862]
8863 [    0     1     2 ... 18350 18351 18352] [8863]
8864 [    0     1     2 ... 18350 18351 18352] [8864]
8865 [    0     1     2 ... 18350 18351 18352] [8865]
8866 [    0     1     2 ... 18350 18351 18352] [8866]
8867 [    0     1     2 ... 18350 18351 18352] [8867]
8868 [    0     1     2 ... 18350 18351 18352] [8868]
8869 [    0     1     2 ... 

9091 [    0     1     2 ... 18350 18351 18352] [9091]
9092 [    0     1     2 ... 18350 18351 18352] [9092]
9093 [    0     1     2 ... 18350 18351 18352] [9093]
9094 [    0     1     2 ... 18350 18351 18352] [9094]
9095 [    0     1     2 ... 18350 18351 18352] [9095]
9096 [    0     1     2 ... 18350 18351 18352] [9096]
9097 [    0     1     2 ... 18350 18351 18352] [9097]
9098 [    0     1     2 ... 18350 18351 18352] [9098]
9099 [    0     1     2 ... 18350 18351 18352] [9099]
9100 [    0     1     2 ... 18350 18351 18352] [9100]
9101 [    0     1     2 ... 18350 18351 18352] [9101]
9102 [    0     1     2 ... 18350 18351 18352] [9102]
9103 [    0     1     2 ... 18350 18351 18352] [9103]
9104 [    0     1     2 ... 18350 18351 18352] [9104]
9105 [    0     1     2 ... 18350 18351 18352] [9105]
9106 [    0     1     2 ... 18350 18351 18352] [9106]
9107 [    0     1     2 ... 18350 18351 18352] [9107]
9108 [    0     1     2 ... 18350 18351 18352] [9108]
9109 [    0     1     2 ... 

9342 [    0     1     2 ... 18350 18351 18352] [9342]
9343 [    0     1     2 ... 18350 18351 18352] [9343]
9344 [    0     1     2 ... 18350 18351 18352] [9344]
9345 [    0     1     2 ... 18350 18351 18352] [9345]
9346 [    0     1     2 ... 18350 18351 18352] [9346]
9347 [    0     1     2 ... 18350 18351 18352] [9347]
9348 [    0     1     2 ... 18350 18351 18352] [9348]
9349 [    0     1     2 ... 18350 18351 18352] [9349]
9350 [    0     1     2 ... 18350 18351 18352] [9350]
9351 [    0     1     2 ... 18350 18351 18352] [9351]
9352 [    0     1     2 ... 18350 18351 18352] [9352]
9353 [    0     1     2 ... 18350 18351 18352] [9353]
9354 [    0     1     2 ... 18350 18351 18352] [9354]
9355 [    0     1     2 ... 18350 18351 18352] [9355]
9356 [    0     1     2 ... 18350 18351 18352] [9356]
9357 [    0     1     2 ... 18350 18351 18352] [9357]
9358 [    0     1     2 ... 18350 18351 18352] [9358]
9359 [    0     1     2 ... 18350 18351 18352] [9359]
9360 [    0     1     2 ... 

9577 [    0     1     2 ... 18350 18351 18352] [9577]
9578 [    0     1     2 ... 18350 18351 18352] [9578]
9579 [    0     1     2 ... 18350 18351 18352] [9579]
9580 [    0     1     2 ... 18350 18351 18352] [9580]
9581 [    0     1     2 ... 18350 18351 18352] [9581]
9582 [    0     1     2 ... 18350 18351 18352] [9582]
9583 [    0     1     2 ... 18350 18351 18352] [9583]
9584 [    0     1     2 ... 18350 18351 18352] [9584]
9585 [    0     1     2 ... 18350 18351 18352] [9585]
9586 [    0     1     2 ... 18350 18351 18352] [9586]
9587 [    0     1     2 ... 18350 18351 18352] [9587]
9588 [    0     1     2 ... 18350 18351 18352] [9588]
9589 [    0     1     2 ... 18350 18351 18352] [9589]
9590 [    0     1     2 ... 18350 18351 18352] [9590]
9591 [    0     1     2 ... 18350 18351 18352] [9591]
9592 [    0     1     2 ... 18350 18351 18352] [9592]
9593 [    0     1     2 ... 18350 18351 18352] [9593]
9594 [    0     1     2 ... 18350 18351 18352] [9594]
9595 [    0     1     2 ... 

9831 [    0     1     2 ... 18350 18351 18352] [9831]
9832 [    0     1     2 ... 18350 18351 18352] [9832]
9833 [    0     1     2 ... 18350 18351 18352] [9833]
9834 [    0     1     2 ... 18350 18351 18352] [9834]
9835 [    0     1     2 ... 18350 18351 18352] [9835]
9836 [    0     1     2 ... 18350 18351 18352] [9836]
9837 [    0     1     2 ... 18350 18351 18352] [9837]
9838 [    0     1     2 ... 18350 18351 18352] [9838]
9839 [    0     1     2 ... 18350 18351 18352] [9839]
9840 [    0     1     2 ... 18350 18351 18352] [9840]
9841 [    0     1     2 ... 18350 18351 18352] [9841]
9842 [    0     1     2 ... 18350 18351 18352] [9842]
9843 [    0     1     2 ... 18350 18351 18352] [9843]
9844 [    0     1     2 ... 18350 18351 18352] [9844]
9845 [    0     1     2 ... 18350 18351 18352] [9845]
9846 [    0     1     2 ... 18350 18351 18352] [9846]
9847 [    0     1     2 ... 18350 18351 18352] [9847]
9848 [    0     1     2 ... 18350 18351 18352] [9848]
9849 [    0     1     2 ... 

10067 [    0     1     2 ... 18350 18351 18352] [10067]
10068 [    0     1     2 ... 18350 18351 18352] [10068]
10069 [    0     1     2 ... 18350 18351 18352] [10069]
10070 [    0     1     2 ... 18350 18351 18352] [10070]
10071 [    0     1     2 ... 18350 18351 18352] [10071]
10072 [    0     1     2 ... 18350 18351 18352] [10072]
10073 [    0     1     2 ... 18350 18351 18352] [10073]
10074 [    0     1     2 ... 18350 18351 18352] [10074]
10075 [    0     1     2 ... 18350 18351 18352] [10075]
10076 [    0     1     2 ... 18350 18351 18352] [10076]
10077 [    0     1     2 ... 18350 18351 18352] [10077]
10078 [    0     1     2 ... 18350 18351 18352] [10078]
10079 [    0     1     2 ... 18350 18351 18352] [10079]
10080 [    0     1     2 ... 18350 18351 18352] [10080]
10081 [    0     1     2 ... 18350 18351 18352] [10081]
10082 [    0     1     2 ... 18350 18351 18352] [10082]
10083 [    0     1     2 ... 18350 18351 18352] [10083]
10084 [    0     1     2 ... 18350 18351 18352] 

10312 [    0     1     2 ... 18350 18351 18352] [10312]
10313 [    0     1     2 ... 18350 18351 18352] [10313]
10314 [    0     1     2 ... 18350 18351 18352] [10314]
10315 [    0     1     2 ... 18350 18351 18352] [10315]
10316 [    0     1     2 ... 18350 18351 18352] [10316]
10317 [    0     1     2 ... 18350 18351 18352] [10317]
10318 [    0     1     2 ... 18350 18351 18352] [10318]
10319 [    0     1     2 ... 18350 18351 18352] [10319]
10320 [    0     1     2 ... 18350 18351 18352] [10320]
10321 [    0     1     2 ... 18350 18351 18352] [10321]
10322 [    0     1     2 ... 18350 18351 18352] [10322]
10323 [    0     1     2 ... 18350 18351 18352] [10323]
10324 [    0     1     2 ... 18350 18351 18352] [10324]
10325 [    0     1     2 ... 18350 18351 18352] [10325]
10326 [    0     1     2 ... 18350 18351 18352] [10326]
10327 [    0     1     2 ... 18350 18351 18352] [10327]
10328 [    0     1     2 ... 18350 18351 18352] [10328]
10329 [    0     1     2 ... 18350 18351 18352] 

10555 [    0     1     2 ... 18350 18351 18352] [10555]
10556 [    0     1     2 ... 18350 18351 18352] [10556]
10557 [    0     1     2 ... 18350 18351 18352] [10557]
10558 [    0     1     2 ... 18350 18351 18352] [10558]
10559 [    0     1     2 ... 18350 18351 18352] [10559]
10560 [    0     1     2 ... 18350 18351 18352] [10560]
10561 [    0     1     2 ... 18350 18351 18352] [10561]
10562 [    0     1     2 ... 18350 18351 18352] [10562]
10563 [    0     1     2 ... 18350 18351 18352] [10563]
10564 [    0     1     2 ... 18350 18351 18352] [10564]
10565 [    0     1     2 ... 18350 18351 18352] [10565]
10566 [    0     1     2 ... 18350 18351 18352] [10566]
10567 [    0     1     2 ... 18350 18351 18352] [10567]
10568 [    0     1     2 ... 18350 18351 18352] [10568]
10569 [    0     1     2 ... 18350 18351 18352] [10569]
10570 [    0     1     2 ... 18350 18351 18352] [10570]
10571 [    0     1     2 ... 18350 18351 18352] [10571]
10572 [    0     1     2 ... 18350 18351 18352] 

10786 [    0     1     2 ... 18350 18351 18352] [10786]
10787 [    0     1     2 ... 18350 18351 18352] [10787]
10788 [    0     1     2 ... 18350 18351 18352] [10788]
10789 [    0     1     2 ... 18350 18351 18352] [10789]
10790 [    0     1     2 ... 18350 18351 18352] [10790]
10791 [    0     1     2 ... 18350 18351 18352] [10791]
10792 [    0     1     2 ... 18350 18351 18352] [10792]
10793 [    0     1     2 ... 18350 18351 18352] [10793]
10794 [    0     1     2 ... 18350 18351 18352] [10794]
10795 [    0     1     2 ... 18350 18351 18352] [10795]
10796 [    0     1     2 ... 18350 18351 18352] [10796]
10797 [    0     1     2 ... 18350 18351 18352] [10797]
10798 [    0     1     2 ... 18350 18351 18352] [10798]
10799 [    0     1     2 ... 18350 18351 18352] [10799]
10800 [    0     1     2 ... 18350 18351 18352] [10800]
10801 [    0     1     2 ... 18350 18351 18352] [10801]
10802 [    0     1     2 ... 18350 18351 18352] [10802]
10803 [    0     1     2 ... 18350 18351 18352] 

11038 [    0     1     2 ... 18350 18351 18352] [11038]
11039 [    0     1     2 ... 18350 18351 18352] [11039]
11040 [    0     1     2 ... 18350 18351 18352] [11040]
11041 [    0     1     2 ... 18350 18351 18352] [11041]
11042 [    0     1     2 ... 18350 18351 18352] [11042]
11043 [    0     1     2 ... 18350 18351 18352] [11043]
11044 [    0     1     2 ... 18350 18351 18352] [11044]
11045 [    0     1     2 ... 18350 18351 18352] [11045]
11046 [    0     1     2 ... 18350 18351 18352] [11046]
11047 [    0     1     2 ... 18350 18351 18352] [11047]
11048 [    0     1     2 ... 18350 18351 18352] [11048]
11049 [    0     1     2 ... 18350 18351 18352] [11049]
11050 [    0     1     2 ... 18350 18351 18352] [11050]
11051 [    0     1     2 ... 18350 18351 18352] [11051]
11052 [    0     1     2 ... 18350 18351 18352] [11052]
11053 [    0     1     2 ... 18350 18351 18352] [11053]
11054 [    0     1     2 ... 18350 18351 18352] [11054]
11055 [    0     1     2 ... 18350 18351 18352] 

11287 [    0     1     2 ... 18350 18351 18352] [11287]
11288 [    0     1     2 ... 18350 18351 18352] [11288]
11289 [    0     1     2 ... 18350 18351 18352] [11289]
11290 [    0     1     2 ... 18350 18351 18352] [11290]
11291 [    0     1     2 ... 18350 18351 18352] [11291]
11292 [    0     1     2 ... 18350 18351 18352] [11292]
11293 [    0     1     2 ... 18350 18351 18352] [11293]
11294 [    0     1     2 ... 18350 18351 18352] [11294]
11295 [    0     1     2 ... 18350 18351 18352] [11295]
11296 [    0     1     2 ... 18350 18351 18352] [11296]
11297 [    0     1     2 ... 18350 18351 18352] [11297]
11298 [    0     1     2 ... 18350 18351 18352] [11298]
11299 [    0     1     2 ... 18350 18351 18352] [11299]
11300 [    0     1     2 ... 18350 18351 18352] [11300]
11301 [    0     1     2 ... 18350 18351 18352] [11301]
11302 [    0     1     2 ... 18350 18351 18352] [11302]
11303 [    0     1     2 ... 18350 18351 18352] [11303]
11304 [    0     1     2 ... 18350 18351 18352] 

11548 [    0     1     2 ... 18350 18351 18352] [11548]
11549 [    0     1     2 ... 18350 18351 18352] [11549]
11550 [    0     1     2 ... 18350 18351 18352] [11550]
11551 [    0     1     2 ... 18350 18351 18352] [11551]
11552 [    0     1     2 ... 18350 18351 18352] [11552]
11553 [    0     1     2 ... 18350 18351 18352] [11553]
11554 [    0     1     2 ... 18350 18351 18352] [11554]
11555 [    0     1     2 ... 18350 18351 18352] [11555]
11556 [    0     1     2 ... 18350 18351 18352] [11556]
11557 [    0     1     2 ... 18350 18351 18352] [11557]
11558 [    0     1     2 ... 18350 18351 18352] [11558]
11559 [    0     1     2 ... 18350 18351 18352] [11559]
11560 [    0     1     2 ... 18350 18351 18352] [11560]
11561 [    0     1     2 ... 18350 18351 18352] [11561]
11562 [    0     1     2 ... 18350 18351 18352] [11562]
11563 [    0     1     2 ... 18350 18351 18352] [11563]
11564 [    0     1     2 ... 18350 18351 18352] [11564]
11565 [    0     1     2 ... 18350 18351 18352] 

11814 [    0     1     2 ... 18350 18351 18352] [11814]
11815 [    0     1     2 ... 18350 18351 18352] [11815]
11816 [    0     1     2 ... 18350 18351 18352] [11816]
11817 [    0     1     2 ... 18350 18351 18352] [11817]
11818 [    0     1     2 ... 18350 18351 18352] [11818]
11819 [    0     1     2 ... 18350 18351 18352] [11819]
11820 [    0     1     2 ... 18350 18351 18352] [11820]
11821 [    0     1     2 ... 18350 18351 18352] [11821]
11822 [    0     1     2 ... 18350 18351 18352] [11822]
11823 [    0     1     2 ... 18350 18351 18352] [11823]
11824 [    0     1     2 ... 18350 18351 18352] [11824]
11825 [    0     1     2 ... 18350 18351 18352] [11825]
11826 [    0     1     2 ... 18350 18351 18352] [11826]
11827 [    0     1     2 ... 18350 18351 18352] [11827]
11828 [    0     1     2 ... 18350 18351 18352] [11828]
11829 [    0     1     2 ... 18350 18351 18352] [11829]
11830 [    0     1     2 ... 18350 18351 18352] [11830]
11831 [    0     1     2 ... 18350 18351 18352] 

12083 [    0     1     2 ... 18350 18351 18352] [12083]
12084 [    0     1     2 ... 18350 18351 18352] [12084]
12085 [    0     1     2 ... 18350 18351 18352] [12085]
12086 [    0     1     2 ... 18350 18351 18352] [12086]
12087 [    0     1     2 ... 18350 18351 18352] [12087]
12088 [    0     1     2 ... 18350 18351 18352] [12088]
12089 [    0     1     2 ... 18350 18351 18352] [12089]
12090 [    0     1     2 ... 18350 18351 18352] [12090]
12091 [    0     1     2 ... 18350 18351 18352] [12091]
12092 [    0     1     2 ... 18350 18351 18352] [12092]
12093 [    0     1     2 ... 18350 18351 18352] [12093]
12094 [    0     1     2 ... 18350 18351 18352] [12094]
12095 [    0     1     2 ... 18350 18351 18352] [12095]
12096 [    0     1     2 ... 18350 18351 18352] [12096]
12097 [    0     1     2 ... 18350 18351 18352] [12097]
12098 [    0     1     2 ... 18350 18351 18352] [12098]
12099 [    0     1     2 ... 18350 18351 18352] [12099]
12100 [    0     1     2 ... 18350 18351 18352] 

12312 [    0     1     2 ... 18350 18351 18352] [12312]
12313 [    0     1     2 ... 18350 18351 18352] [12313]
12314 [    0     1     2 ... 18350 18351 18352] [12314]
12315 [    0     1     2 ... 18350 18351 18352] [12315]
12316 [    0     1     2 ... 18350 18351 18352] [12316]
12317 [    0     1     2 ... 18350 18351 18352] [12317]
12318 [    0     1     2 ... 18350 18351 18352] [12318]
12319 [    0     1     2 ... 18350 18351 18352] [12319]
12320 [    0     1     2 ... 18350 18351 18352] [12320]
12321 [    0     1     2 ... 18350 18351 18352] [12321]
12322 [    0     1     2 ... 18350 18351 18352] [12322]
12323 [    0     1     2 ... 18350 18351 18352] [12323]
12324 [    0     1     2 ... 18350 18351 18352] [12324]
12325 [    0     1     2 ... 18350 18351 18352] [12325]
12326 [    0     1     2 ... 18350 18351 18352] [12326]
12327 [    0     1     2 ... 18350 18351 18352] [12327]
12328 [    0     1     2 ... 18350 18351 18352] [12328]
12329 [    0     1     2 ... 18350 18351 18352] 

12571 [    0     1     2 ... 18350 18351 18352] [12571]
12572 [    0     1     2 ... 18350 18351 18352] [12572]
12573 [    0     1     2 ... 18350 18351 18352] [12573]
12574 [    0     1     2 ... 18350 18351 18352] [12574]
12575 [    0     1     2 ... 18350 18351 18352] [12575]
12576 [    0     1     2 ... 18350 18351 18352] [12576]
12577 [    0     1     2 ... 18350 18351 18352] [12577]
12578 [    0     1     2 ... 18350 18351 18352] [12578]
12579 [    0     1     2 ... 18350 18351 18352] [12579]
12580 [    0     1     2 ... 18350 18351 18352] [12580]
12581 [    0     1     2 ... 18350 18351 18352] [12581]
12582 [    0     1     2 ... 18350 18351 18352] [12582]
12583 [    0     1     2 ... 18350 18351 18352] [12583]
12584 [    0     1     2 ... 18350 18351 18352] [12584]
12585 [    0     1     2 ... 18350 18351 18352] [12585]
12586 [    0     1     2 ... 18350 18351 18352] [12586]
12587 [    0     1     2 ... 18350 18351 18352] [12587]
12588 [    0     1     2 ... 18350 18351 18352] 

12799 [    0     1     2 ... 18350 18351 18352] [12799]
12800 [    0     1     2 ... 18350 18351 18352] [12800]
12801 [    0     1     2 ... 18350 18351 18352] [12801]
12802 [    0     1     2 ... 18350 18351 18352] [12802]
12803 [    0     1     2 ... 18350 18351 18352] [12803]
12804 [    0     1     2 ... 18350 18351 18352] [12804]
12805 [    0     1     2 ... 18350 18351 18352] [12805]
12806 [    0     1     2 ... 18350 18351 18352] [12806]
12807 [    0     1     2 ... 18350 18351 18352] [12807]
12808 [    0     1     2 ... 18350 18351 18352] [12808]
12809 [    0     1     2 ... 18350 18351 18352] [12809]
12810 [    0     1     2 ... 18350 18351 18352] [12810]
12811 [    0     1     2 ... 18350 18351 18352] [12811]
12812 [    0     1     2 ... 18350 18351 18352] [12812]
12813 [    0     1     2 ... 18350 18351 18352] [12813]
12814 [    0     1     2 ... 18350 18351 18352] [12814]
12815 [    0     1     2 ... 18350 18351 18352] [12815]
12816 [    0     1     2 ... 18350 18351 18352] 

13043 [    0     1     2 ... 18350 18351 18352] [13043]
13044 [    0     1     2 ... 18350 18351 18352] [13044]
13045 [    0     1     2 ... 18350 18351 18352] [13045]
13046 [    0     1     2 ... 18350 18351 18352] [13046]
13047 [    0     1     2 ... 18350 18351 18352] [13047]
13048 [    0     1     2 ... 18350 18351 18352] [13048]
13049 [    0     1     2 ... 18350 18351 18352] [13049]
13050 [    0     1     2 ... 18350 18351 18352] [13050]
13051 [    0     1     2 ... 18350 18351 18352] [13051]
13052 [    0     1     2 ... 18350 18351 18352] [13052]
13053 [    0     1     2 ... 18350 18351 18352] [13053]
13054 [    0     1     2 ... 18350 18351 18352] [13054]
13055 [    0     1     2 ... 18350 18351 18352] [13055]
13056 [    0     1     2 ... 18350 18351 18352] [13056]
13057 [    0     1     2 ... 18350 18351 18352] [13057]
13058 [    0     1     2 ... 18350 18351 18352] [13058]
13059 [    0     1     2 ... 18350 18351 18352] [13059]
13060 [    0     1     2 ... 18350 18351 18352] 

13290 [    0     1     2 ... 18350 18351 18352] [13290]
13291 [    0     1     2 ... 18350 18351 18352] [13291]
13292 [    0     1     2 ... 18350 18351 18352] [13292]
13293 [    0     1     2 ... 18350 18351 18352] [13293]
13294 [    0     1     2 ... 18350 18351 18352] [13294]
13295 [    0     1     2 ... 18350 18351 18352] [13295]
13296 [    0     1     2 ... 18350 18351 18352] [13296]
13297 [    0     1     2 ... 18350 18351 18352] [13297]
13298 [    0     1     2 ... 18350 18351 18352] [13298]
13299 [    0     1     2 ... 18350 18351 18352] [13299]
13300 [    0     1     2 ... 18350 18351 18352] [13300]
13301 [    0     1     2 ... 18350 18351 18352] [13301]
13302 [    0     1     2 ... 18350 18351 18352] [13302]
13303 [    0     1     2 ... 18350 18351 18352] [13303]
13304 [    0     1     2 ... 18350 18351 18352] [13304]
13305 [    0     1     2 ... 18350 18351 18352] [13305]
13306 [    0     1     2 ... 18350 18351 18352] [13306]
13307 [    0     1     2 ... 18350 18351 18352] 

13526 [    0     1     2 ... 18350 18351 18352] [13526]
13527 [    0     1     2 ... 18350 18351 18352] [13527]
13528 [    0     1     2 ... 18350 18351 18352] [13528]
13529 [    0     1     2 ... 18350 18351 18352] [13529]
13530 [    0     1     2 ... 18350 18351 18352] [13530]
13531 [    0     1     2 ... 18350 18351 18352] [13531]
13532 [    0     1     2 ... 18350 18351 18352] [13532]
13533 [    0     1     2 ... 18350 18351 18352] [13533]
13534 [    0     1     2 ... 18350 18351 18352] [13534]
13535 [    0     1     2 ... 18350 18351 18352] [13535]
13536 [    0     1     2 ... 18350 18351 18352] [13536]
13537 [    0     1     2 ... 18350 18351 18352] [13537]
13538 [    0     1     2 ... 18350 18351 18352] [13538]
13539 [    0     1     2 ... 18350 18351 18352] [13539]
13540 [    0     1     2 ... 18350 18351 18352] [13540]
13541 [    0     1     2 ... 18350 18351 18352] [13541]
13542 [    0     1     2 ... 18350 18351 18352] [13542]
13543 [    0     1     2 ... 18350 18351 18352] 

13781 [    0     1     2 ... 18350 18351 18352] [13781]
13782 [    0     1     2 ... 18350 18351 18352] [13782]
13783 [    0     1     2 ... 18350 18351 18352] [13783]
13784 [    0     1     2 ... 18350 18351 18352] [13784]
13785 [    0     1     2 ... 18350 18351 18352] [13785]
13786 [    0     1     2 ... 18350 18351 18352] [13786]
13787 [    0     1     2 ... 18350 18351 18352] [13787]
13788 [    0     1     2 ... 18350 18351 18352] [13788]
13789 [    0     1     2 ... 18350 18351 18352] [13789]
13790 [    0     1     2 ... 18350 18351 18352] [13790]
13791 [    0     1     2 ... 18350 18351 18352] [13791]
13792 [    0     1     2 ... 18350 18351 18352] [13792]
13793 [    0     1     2 ... 18350 18351 18352] [13793]
13794 [    0     1     2 ... 18350 18351 18352] [13794]
13795 [    0     1     2 ... 18350 18351 18352] [13795]
13796 [    0     1     2 ... 18350 18351 18352] [13796]
13797 [    0     1     2 ... 18350 18351 18352] [13797]
13798 [    0     1     2 ... 18350 18351 18352] 

14006 [    0     1     2 ... 18350 18351 18352] [14006]
14007 [    0     1     2 ... 18350 18351 18352] [14007]
14008 [    0     1     2 ... 18350 18351 18352] [14008]
14009 [    0     1     2 ... 18350 18351 18352] [14009]
14010 [    0     1     2 ... 18350 18351 18352] [14010]
14011 [    0     1     2 ... 18350 18351 18352] [14011]
14012 [    0     1     2 ... 18350 18351 18352] [14012]
14013 [    0     1     2 ... 18350 18351 18352] [14013]
14014 [    0     1     2 ... 18350 18351 18352] [14014]
14015 [    0     1     2 ... 18350 18351 18352] [14015]
14016 [    0     1     2 ... 18350 18351 18352] [14016]
14017 [    0     1     2 ... 18350 18351 18352] [14017]
14018 [    0     1     2 ... 18350 18351 18352] [14018]
14019 [    0     1     2 ... 18350 18351 18352] [14019]
14020 [    0     1     2 ... 18350 18351 18352] [14020]
14021 [    0     1     2 ... 18350 18351 18352] [14021]
14022 [    0     1     2 ... 18350 18351 18352] [14022]
14023 [    0     1     2 ... 18350 18351 18352] 

14249 [    0     1     2 ... 18350 18351 18352] [14249]
14250 [    0     1     2 ... 18350 18351 18352] [14250]
14251 [    0     1     2 ... 18350 18351 18352] [14251]
14252 [    0     1     2 ... 18350 18351 18352] [14252]
14253 [    0     1     2 ... 18350 18351 18352] [14253]
14254 [    0     1     2 ... 18350 18351 18352] [14254]
14255 [    0     1     2 ... 18350 18351 18352] [14255]
14256 [    0     1     2 ... 18350 18351 18352] [14256]
14257 [    0     1     2 ... 18350 18351 18352] [14257]
14258 [    0     1     2 ... 18350 18351 18352] [14258]
14259 [    0     1     2 ... 18350 18351 18352] [14259]
14260 [    0     1     2 ... 18350 18351 18352] [14260]
14261 [    0     1     2 ... 18350 18351 18352] [14261]
14262 [    0     1     2 ... 18350 18351 18352] [14262]
14263 [    0     1     2 ... 18350 18351 18352] [14263]
14264 [    0     1     2 ... 18350 18351 18352] [14264]
14265 [    0     1     2 ... 18350 18351 18352] [14265]
14266 [    0     1     2 ... 18350 18351 18352] 

14483 [    0     1     2 ... 18350 18351 18352] [14483]
14484 [    0     1     2 ... 18350 18351 18352] [14484]
14485 [    0     1     2 ... 18350 18351 18352] [14485]
14486 [    0     1     2 ... 18350 18351 18352] [14486]
14487 [    0     1     2 ... 18350 18351 18352] [14487]
14488 [    0     1     2 ... 18350 18351 18352] [14488]
14489 [    0     1     2 ... 18350 18351 18352] [14489]
14490 [    0     1     2 ... 18350 18351 18352] [14490]
14491 [    0     1     2 ... 18350 18351 18352] [14491]
14492 [    0     1     2 ... 18350 18351 18352] [14492]
14493 [    0     1     2 ... 18350 18351 18352] [14493]
14494 [    0     1     2 ... 18350 18351 18352] [14494]
14495 [    0     1     2 ... 18350 18351 18352] [14495]
14496 [    0     1     2 ... 18350 18351 18352] [14496]
14497 [    0     1     2 ... 18350 18351 18352] [14497]
14498 [    0     1     2 ... 18350 18351 18352] [14498]
14499 [    0     1     2 ... 18350 18351 18352] [14499]
14500 [    0     1     2 ... 18350 18351 18352] 

14716 [    0     1     2 ... 18350 18351 18352] [14716]
14717 [    0     1     2 ... 18350 18351 18352] [14717]
14718 [    0     1     2 ... 18350 18351 18352] [14718]
14719 [    0     1     2 ... 18350 18351 18352] [14719]
14720 [    0     1     2 ... 18350 18351 18352] [14720]
14721 [    0     1     2 ... 18350 18351 18352] [14721]
14722 [    0     1     2 ... 18350 18351 18352] [14722]
14723 [    0     1     2 ... 18350 18351 18352] [14723]
14724 [    0     1     2 ... 18350 18351 18352] [14724]
14725 [    0     1     2 ... 18350 18351 18352] [14725]
14726 [    0     1     2 ... 18350 18351 18352] [14726]
14727 [    0     1     2 ... 18350 18351 18352] [14727]
14728 [    0     1     2 ... 18350 18351 18352] [14728]
14729 [    0     1     2 ... 18350 18351 18352] [14729]
14730 [    0     1     2 ... 18350 18351 18352] [14730]
14731 [    0     1     2 ... 18350 18351 18352] [14731]
14732 [    0     1     2 ... 18350 18351 18352] [14732]
14733 [    0     1     2 ... 18350 18351 18352] 

14960 [    0     1     2 ... 18350 18351 18352] [14960]
14961 [    0     1     2 ... 18350 18351 18352] [14961]
14962 [    0     1     2 ... 18350 18351 18352] [14962]
14963 [    0     1     2 ... 18350 18351 18352] [14963]
14964 [    0     1     2 ... 18350 18351 18352] [14964]
14965 [    0     1     2 ... 18350 18351 18352] [14965]
14966 [    0     1     2 ... 18350 18351 18352] [14966]
14967 [    0     1     2 ... 18350 18351 18352] [14967]
14968 [    0     1     2 ... 18350 18351 18352] [14968]
14969 [    0     1     2 ... 18350 18351 18352] [14969]
14970 [    0     1     2 ... 18350 18351 18352] [14970]
14971 [    0     1     2 ... 18350 18351 18352] [14971]
14972 [    0     1     2 ... 18350 18351 18352] [14972]
14973 [    0     1     2 ... 18350 18351 18352] [14973]
14974 [    0     1     2 ... 18350 18351 18352] [14974]
14975 [    0     1     2 ... 18350 18351 18352] [14975]
14976 [    0     1     2 ... 18350 18351 18352] [14976]
14977 [    0     1     2 ... 18350 18351 18352] 

15204 [    0     1     2 ... 18350 18351 18352] [15204]
15205 [    0     1     2 ... 18350 18351 18352] [15205]
15206 [    0     1     2 ... 18350 18351 18352] [15206]
15207 [    0     1     2 ... 18350 18351 18352] [15207]
15208 [    0     1     2 ... 18350 18351 18352] [15208]
15209 [    0     1     2 ... 18350 18351 18352] [15209]
15210 [    0     1     2 ... 18350 18351 18352] [15210]
15211 [    0     1     2 ... 18350 18351 18352] [15211]
15212 [    0     1     2 ... 18350 18351 18352] [15212]
15213 [    0     1     2 ... 18350 18351 18352] [15213]
15214 [    0     1     2 ... 18350 18351 18352] [15214]
15215 [    0     1     2 ... 18350 18351 18352] [15215]
15216 [    0     1     2 ... 18350 18351 18352] [15216]
15217 [    0     1     2 ... 18350 18351 18352] [15217]
15218 [    0     1     2 ... 18350 18351 18352] [15218]
15219 [    0     1     2 ... 18350 18351 18352] [15219]
15220 [    0     1     2 ... 18350 18351 18352] [15220]
15221 [    0     1     2 ... 18350 18351 18352] 

15441 [    0     1     2 ... 18350 18351 18352] [15441]
15442 [    0     1     2 ... 18350 18351 18352] [15442]
15443 [    0     1     2 ... 18350 18351 18352] [15443]
15444 [    0     1     2 ... 18350 18351 18352] [15444]
15445 [    0     1     2 ... 18350 18351 18352] [15445]
15446 [    0     1     2 ... 18350 18351 18352] [15446]
15447 [    0     1     2 ... 18350 18351 18352] [15447]
15448 [    0     1     2 ... 18350 18351 18352] [15448]
15449 [    0     1     2 ... 18350 18351 18352] [15449]
15450 [    0     1     2 ... 18350 18351 18352] [15450]
15451 [    0     1     2 ... 18350 18351 18352] [15451]
15452 [    0     1     2 ... 18350 18351 18352] [15452]
15453 [    0     1     2 ... 18350 18351 18352] [15453]
15454 [    0     1     2 ... 18350 18351 18352] [15454]
15455 [    0     1     2 ... 18350 18351 18352] [15455]
15456 [    0     1     2 ... 18350 18351 18352] [15456]
15457 [    0     1     2 ... 18350 18351 18352] [15457]
15458 [    0     1     2 ... 18350 18351 18352] 

15683 [    0     1     2 ... 18350 18351 18352] [15683]
15684 [    0     1     2 ... 18350 18351 18352] [15684]
15685 [    0     1     2 ... 18350 18351 18352] [15685]
15686 [    0     1     2 ... 18350 18351 18352] [15686]
15687 [    0     1     2 ... 18350 18351 18352] [15687]
15688 [    0     1     2 ... 18350 18351 18352] [15688]
15689 [    0     1     2 ... 18350 18351 18352] [15689]
15690 [    0     1     2 ... 18350 18351 18352] [15690]
15691 [    0     1     2 ... 18350 18351 18352] [15691]
15692 [    0     1     2 ... 18350 18351 18352] [15692]
15693 [    0     1     2 ... 18350 18351 18352] [15693]
15694 [    0     1     2 ... 18350 18351 18352] [15694]
15695 [    0     1     2 ... 18350 18351 18352] [15695]
15696 [    0     1     2 ... 18350 18351 18352] [15696]
15697 [    0     1     2 ... 18350 18351 18352] [15697]
15698 [    0     1     2 ... 18350 18351 18352] [15698]
15699 [    0     1     2 ... 18350 18351 18352] [15699]
15700 [    0     1     2 ... 18350 18351 18352] 

15917 [    0     1     2 ... 18350 18351 18352] [15917]
15918 [    0     1     2 ... 18350 18351 18352] [15918]
15919 [    0     1     2 ... 18350 18351 18352] [15919]
15920 [    0     1     2 ... 18350 18351 18352] [15920]
15921 [    0     1     2 ... 18350 18351 18352] [15921]
15922 [    0     1     2 ... 18350 18351 18352] [15922]
15923 [    0     1     2 ... 18350 18351 18352] [15923]
15924 [    0     1     2 ... 18350 18351 18352] [15924]
15925 [    0     1     2 ... 18350 18351 18352] [15925]
15926 [    0     1     2 ... 18350 18351 18352] [15926]
15927 [    0     1     2 ... 18350 18351 18352] [15927]
15928 [    0     1     2 ... 18350 18351 18352] [15928]
15929 [    0     1     2 ... 18350 18351 18352] [15929]
15930 [    0     1     2 ... 18350 18351 18352] [15930]
15931 [    0     1     2 ... 18350 18351 18352] [15931]
15932 [    0     1     2 ... 18350 18351 18352] [15932]
15933 [    0     1     2 ... 18350 18351 18352] [15933]
15934 [    0     1     2 ... 18350 18351 18352] 

16150 [    0     1     2 ... 18350 18351 18352] [16150]
16151 [    0     1     2 ... 18350 18351 18352] [16151]
16152 [    0     1     2 ... 18350 18351 18352] [16152]
16153 [    0     1     2 ... 18350 18351 18352] [16153]
16154 [    0     1     2 ... 18350 18351 18352] [16154]
16155 [    0     1     2 ... 18350 18351 18352] [16155]
16156 [    0     1     2 ... 18350 18351 18352] [16156]
16157 [    0     1     2 ... 18350 18351 18352] [16157]
16158 [    0     1     2 ... 18350 18351 18352] [16158]
16159 [    0     1     2 ... 18350 18351 18352] [16159]
16160 [    0     1     2 ... 18350 18351 18352] [16160]
16161 [    0     1     2 ... 18350 18351 18352] [16161]
16162 [    0     1     2 ... 18350 18351 18352] [16162]
16163 [    0     1     2 ... 18350 18351 18352] [16163]
16164 [    0     1     2 ... 18350 18351 18352] [16164]
16165 [    0     1     2 ... 18350 18351 18352] [16165]
16166 [    0     1     2 ... 18350 18351 18352] [16166]
16167 [    0     1     2 ... 18350 18351 18352] 

16392 [    0     1     2 ... 18350 18351 18352] [16392]
16393 [    0     1     2 ... 18350 18351 18352] [16393]
16394 [    0     1     2 ... 18350 18351 18352] [16394]
16395 [    0     1     2 ... 18350 18351 18352] [16395]
16396 [    0     1     2 ... 18350 18351 18352] [16396]
16397 [    0     1     2 ... 18350 18351 18352] [16397]
16398 [    0     1     2 ... 18350 18351 18352] [16398]
16399 [    0     1     2 ... 18350 18351 18352] [16399]
16400 [    0     1     2 ... 18350 18351 18352] [16400]
16401 [    0     1     2 ... 18350 18351 18352] [16401]
16402 [    0     1     2 ... 18350 18351 18352] [16402]
16403 [    0     1     2 ... 18350 18351 18352] [16403]
16404 [    0     1     2 ... 18350 18351 18352] [16404]
16405 [    0     1     2 ... 18350 18351 18352] [16405]
16406 [    0     1     2 ... 18350 18351 18352] [16406]
16407 [    0     1     2 ... 18350 18351 18352] [16407]
16408 [    0     1     2 ... 18350 18351 18352] [16408]
16409 [    0     1     2 ... 18350 18351 18352] 

16626 [    0     1     2 ... 18350 18351 18352] [16626]
16627 [    0     1     2 ... 18350 18351 18352] [16627]
16628 [    0     1     2 ... 18350 18351 18352] [16628]
16629 [    0     1     2 ... 18350 18351 18352] [16629]
16630 [    0     1     2 ... 18350 18351 18352] [16630]
16631 [    0     1     2 ... 18350 18351 18352] [16631]
16632 [    0     1     2 ... 18350 18351 18352] [16632]
16633 [    0     1     2 ... 18350 18351 18352] [16633]
16634 [    0     1     2 ... 18350 18351 18352] [16634]
16635 [    0     1     2 ... 18350 18351 18352] [16635]
16636 [    0     1     2 ... 18350 18351 18352] [16636]
16637 [    0     1     2 ... 18350 18351 18352] [16637]
16638 [    0     1     2 ... 18350 18351 18352] [16638]
16639 [    0     1     2 ... 18350 18351 18352] [16639]
16640 [    0     1     2 ... 18350 18351 18352] [16640]
16641 [    0     1     2 ... 18350 18351 18352] [16641]
16642 [    0     1     2 ... 18350 18351 18352] [16642]
16643 [    0     1     2 ... 18350 18351 18352] 

16888 [    0     1     2 ... 18350 18351 18352] [16888]
16889 [    0     1     2 ... 18350 18351 18352] [16889]
16890 [    0     1     2 ... 18350 18351 18352] [16890]
16891 [    0     1     2 ... 18350 18351 18352] [16891]
16892 [    0     1     2 ... 18350 18351 18352] [16892]
16893 [    0     1     2 ... 18350 18351 18352] [16893]
16894 [    0     1     2 ... 18350 18351 18352] [16894]
16895 [    0     1     2 ... 18350 18351 18352] [16895]
16896 [    0     1     2 ... 18350 18351 18352] [16896]
16897 [    0     1     2 ... 18350 18351 18352] [16897]
16898 [    0     1     2 ... 18350 18351 18352] [16898]
16899 [    0     1     2 ... 18350 18351 18352] [16899]
16900 [    0     1     2 ... 18350 18351 18352] [16900]
16901 [    0     1     2 ... 18350 18351 18352] [16901]
16902 [    0     1     2 ... 18350 18351 18352] [16902]
16903 [    0     1     2 ... 18350 18351 18352] [16903]
16904 [    0     1     2 ... 18350 18351 18352] [16904]
16905 [    0     1     2 ... 18350 18351 18352] 

17150 [    0     1     2 ... 18350 18351 18352] [17150]
17151 [    0     1     2 ... 18350 18351 18352] [17151]
17152 [    0     1     2 ... 18350 18351 18352] [17152]
17153 [    0     1     2 ... 18350 18351 18352] [17153]
17154 [    0     1     2 ... 18350 18351 18352] [17154]
17155 [    0     1     2 ... 18350 18351 18352] [17155]
17156 [    0     1     2 ... 18350 18351 18352] [17156]
17157 [    0     1     2 ... 18350 18351 18352] [17157]
17158 [    0     1     2 ... 18350 18351 18352] [17158]
17159 [    0     1     2 ... 18350 18351 18352] [17159]
17160 [    0     1     2 ... 18350 18351 18352] [17160]
17161 [    0     1     2 ... 18350 18351 18352] [17161]
17162 [    0     1     2 ... 18350 18351 18352] [17162]
17163 [    0     1     2 ... 18350 18351 18352] [17163]
17164 [    0     1     2 ... 18350 18351 18352] [17164]
17165 [    0     1     2 ... 18350 18351 18352] [17165]
17166 [    0     1     2 ... 18350 18351 18352] [17166]
17167 [    0     1     2 ... 18350 18351 18352] 

17419 [    0     1     2 ... 18350 18351 18352] [17419]
17420 [    0     1     2 ... 18350 18351 18352] [17420]
17421 [    0     1     2 ... 18350 18351 18352] [17421]
17422 [    0     1     2 ... 18350 18351 18352] [17422]
17423 [    0     1     2 ... 18350 18351 18352] [17423]
17424 [    0     1     2 ... 18350 18351 18352] [17424]
17425 [    0     1     2 ... 18350 18351 18352] [17425]
17426 [    0     1     2 ... 18350 18351 18352] [17426]
17427 [    0     1     2 ... 18350 18351 18352] [17427]
17428 [    0     1     2 ... 18350 18351 18352] [17428]
17429 [    0     1     2 ... 18350 18351 18352] [17429]
17430 [    0     1     2 ... 18350 18351 18352] [17430]
17431 [    0     1     2 ... 18350 18351 18352] [17431]
17432 [    0     1     2 ... 18350 18351 18352] [17432]
17433 [    0     1     2 ... 18350 18351 18352] [17433]
17434 [    0     1     2 ... 18350 18351 18352] [17434]
17435 [    0     1     2 ... 18350 18351 18352] [17435]
17436 [    0     1     2 ... 18350 18351 18352] 

17676 [    0     1     2 ... 18350 18351 18352] [17676]
17677 [    0     1     2 ... 18350 18351 18352] [17677]
17678 [    0     1     2 ... 18350 18351 18352] [17678]
17679 [    0     1     2 ... 18350 18351 18352] [17679]
17680 [    0     1     2 ... 18350 18351 18352] [17680]
17681 [    0     1     2 ... 18350 18351 18352] [17681]
17682 [    0     1     2 ... 18350 18351 18352] [17682]
17683 [    0     1     2 ... 18350 18351 18352] [17683]
17684 [    0     1     2 ... 18350 18351 18352] [17684]
17685 [    0     1     2 ... 18350 18351 18352] [17685]
17686 [    0     1     2 ... 18350 18351 18352] [17686]
17687 [    0     1     2 ... 18350 18351 18352] [17687]
17688 [    0     1     2 ... 18350 18351 18352] [17688]
17689 [    0     1     2 ... 18350 18351 18352] [17689]
17690 [    0     1     2 ... 18350 18351 18352] [17690]
17691 [    0     1     2 ... 18350 18351 18352] [17691]
17692 [    0     1     2 ... 18350 18351 18352] [17692]
17693 [    0     1     2 ... 18350 18351 18352] 

17936 [    0     1     2 ... 18350 18351 18352] [17936]
17937 [    0     1     2 ... 18350 18351 18352] [17937]
17938 [    0     1     2 ... 18350 18351 18352] [17938]
17939 [    0     1     2 ... 18350 18351 18352] [17939]
17940 [    0     1     2 ... 18350 18351 18352] [17940]
17941 [    0     1     2 ... 18350 18351 18352] [17941]
17942 [    0     1     2 ... 18350 18351 18352] [17942]
17943 [    0     1     2 ... 18350 18351 18352] [17943]
17944 [    0     1     2 ... 18350 18351 18352] [17944]
17945 [    0     1     2 ... 18350 18351 18352] [17945]
17946 [    0     1     2 ... 18350 18351 18352] [17946]
17947 [    0     1     2 ... 18350 18351 18352] [17947]
17948 [    0     1     2 ... 18350 18351 18352] [17948]
17949 [    0     1     2 ... 18350 18351 18352] [17949]
17950 [    0     1     2 ... 18350 18351 18352] [17950]
17951 [    0     1     2 ... 18350 18351 18352] [17951]
17952 [    0     1     2 ... 18350 18351 18352] [17952]
17953 [    0     1     2 ... 18350 18351 18352] 

18146 [    0     1     2 ... 18350 18351 18352] [18146]
18147 [    0     1     2 ... 18350 18351 18352] [18147]
18148 [    0     1     2 ... 18350 18351 18352] [18148]
18149 [    0     1     2 ... 18350 18351 18352] [18149]
18150 [    0     1     2 ... 18350 18351 18352] [18150]
18151 [    0     1     2 ... 18350 18351 18352] [18151]
18152 [    0     1     2 ... 18350 18351 18352] [18152]
18153 [    0     1     2 ... 18350 18351 18352] [18153]
18154 [    0     1     2 ... 18350 18351 18352] [18154]
18155 [    0     1     2 ... 18350 18351 18352] [18155]
18156 [    0     1     2 ... 18350 18351 18352] [18156]
18157 [    0     1     2 ... 18350 18351 18352] [18157]
18158 [    0     1     2 ... 18350 18351 18352] [18158]
18159 [    0     1     2 ... 18350 18351 18352] [18159]
18160 [    0     1     2 ... 18350 18351 18352] [18160]
18161 [    0     1     2 ... 18350 18351 18352] [18161]
18162 [    0     1     2 ... 18350 18351 18352] [18162]
18163 [    0     1     2 ... 18350 18351 18352] 

In [40]:
## shufflesplit
from sklearn.model_selection import ShuffleSplit
ssp = ShuffleSplit(n_splits=5, test_size=0.2, random_state=1)
for train_idx, valid_idx in ssp.split(train_valid_data):
    print(train_idx, valid_idx)

[ 5798  7100 13011 ...  5192 12172   235] [12785  6270   201 ... 15693 16978  9203]
[ 8711 15574   105 ...  7334  5271  2071] [  373  3433 17289 ...  1577  6524 17695]
[  873  6821  1776 ...  6721 12754  9574] [11787 13717 14828 ...   879  6546 17862]
[ 2258 13832  4562 ... 10717 16357 17420] [13016  1048 17172 ...  9373  2412  1293]
[11193 11837  6989 ... 14699 14443 16100] [11517 17852  2653 ...  3991 16576  6324]


In [1]:
import pandas as pd
import os
import shutil

In [2]:
data = pd.read_csv('/Users/xiaoqiang/Mlearning/汽车分类/train.csv')

In [5]:
data

image  label
0     11185      5
1     76332      3
2     16686      0
3     45978      5
4     92662      1
...     ...    ...
4495  35543      1
4496  47394      3
4497  65614      3
4498  16934      0
4499  24091      2

[4500 rows x 2 columns]

In [6]:
k_fold = ['fold1', 'fold2', 'fold3', 'fold4', 'fold5']

image  label
0    11185      5
1    76332      3
2    16686      0
3    45978      5
4    92662      1
..     ...    ...
195   3003      4
196  44316      3
197  31440      1
198   9420      4
199  13524      5

[200 rows x 2 columns]

In [11]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5)
for train_idx, valid_idx in kfold.split(range(4500)):
    print(train_idx)
    print(len(train_idx))

[ 900  901  902 ... 4497 4498 4499]
3600
[   0    1    2 ... 4497 4498 4499]
3600
[   0    1    2 ... 4497 4498 4499]
3600
[   0    1    2 ... 4497 4498 4499]
3600
[   0    1    2 ... 3597 3598 3599]
3600


In [12]:
data

image  label
0     11185      5
1     76332      3
2     16686      0
3     45978      5
4     92662      1
...     ...    ...
4495  35543      1
4496  47394      3
4497  65614      3
4498  16934      0
4499  24091      2

[4500 rows x 2 columns]

In [17]:
weight = data.groupby('label').count()

In [18]:
weight

image
label       
0        579
1        556
2        572
3        584
4        611
5        583
6        604
7        411

In [40]:
# 权重取样
val_image = []
train_image = []
for i in range(8):
    new_data = data[data['label']==i]
    if i == 7:
        val_image.extend(new_data[:95]['image'])
        train_image.extend(new_data[95:]['image'])
    else:
        val_image.extend(new_data[:115]['image'])
        train_image.extend(new_data[115:]['image'])

In [42]:
len(val_image)

900

In [43]:
len(train_image)

3600

In [46]:
train_df = pd.DataFrame({'image':train_image, 'label':data[data['image']==i for i in train_image]})

SyntaxError: invalid syntax (2621017350.py, line 1)

In [21]:
import numpy as np
import torch
classes, counts = np.unique(data['label'], return_counts=True)
num_class = classes.shape[0]
count = counts.max()
weights = np.zeros(len(data))
for c in classes:
    freq_c = np.sum(data['label']==c)
    weights[data['label']==c] = len(data)/freq_c
weights = list(weights)
sampler = torch.utils.data.WeightedRandomSampler(weights, int(num_class*count))
len(sampler)

4888

In [30]:
list(index)

TypeError: 'NoneType' object is not iterable

In [47]:
data

image  label
0     11185      5
1     76332      3
2     16686      0
3     45978      5
4     92662      1
...     ...    ...
4495  35543      1
4496  47394      3
4497  65614      3
4498  16934      0
4499  24091      2

[4500 rows x 2 columns]

In [48]:
val_df = data[:900]

In [52]:
train_df = data[900:]

In [53]:
train_df

image  label
900   22016      2
901    4932      6
902   69011      3
903   69140      1
904   42889      3
...     ...    ...
4495  35543      1
4496  47394      3
4497  65614      3
4498  16934      0
4499  24091      2

[3600 rows x 2 columns]

In [55]:
train_df.to_csv('train.csv', index=False)
val_df.to_csv('val.csv', index=False)

In [56]:
train_data = pd.read_csv('train.csv')
val_data = pd.read_csv('val.csv')

In [61]:
train =list(train_data['image'])
val = list(val_data['image'])

In [68]:
file_list = os.listdir('/Users/xiaoqiang/Mlearning/汽车分类/train_data')

In [69]:
file_list

['14147.jpg',
 '23933.jpg',
 '82643.jpg',
 '7078.jpg',
 '80732.jpg',
 '99263.jpg',
 '89070.jpg',
 '21856.jpg',
 '16022.jpg',
 '42315.jpg',
 '837.jpg',
 '32802.jpg',
 '7722.jpg',
 '98141.jpg',
 '1435.jpg',
 '83207.jpg',
 '30967.jpg',
 '94009.jpg',
 '18755.jpg',
 '36443.jpg',
 '64305.jpg',
 '5874.jpg',
 '79432.jpg',
 '79426.jpg',
 '48823.jpg',
 '22422.jpg',
 '65769.jpg',
 '37749.jpg',
 '28641.jpg',
 '46826.jpg',
 '30768.jpg',
 '25403.jpg',
 '23066.jpg',
 '45485.jpg',
 '23700.jpg',
 '84756.jpg',
 '94223.jpg',
 '61902.jpg',
 '98419.jpg',
 '77812.jpg',
 '5479.jpg',
 '14437.jpg',
 '13358.jpg',
 '91401.jpg',
 '63697.jpg',
 '36866.jpg',
 '36872.jpg',
 '28494.jpg',
 '86169.jpg',
 '97064.jpg',
 '95698.jpg',
 '90086.jpg',
 '29761.jpg',
 '3975.jpg',
 '82496.jpg',
 '86196.jpg',
 '62562.jpg',
 '31884.jpg',
 '77609.jpg',
 '38136.jpg',
 '21301.jpg',
 '6825.jpg',
 '63126.jpg',
 '3791.jpg',
 '27764.jpg',
 '43590.jpg',
 '2276.jpg',
 '4161.jpg',
 '14231.jpg',
 '12640.jpg',
 '85528.jpg',
 '27189.jpg',
 '80

In [78]:
os.makedirs('train_dir', exist_ok=True)
os.makedirs('val_dir', exist_ok=True)
for i in file_list:
    if int(i.split('.')[0]) in train:
        shutil.copy(os.path.join('/Users/xiaoqiang/Mlearning/汽车分类/train_data', i), 'train_dir')
    else:
        shutil.copy(os.path.join('/Users/xiaoqiang/Mlearning/汽车分类/train_data', i), 'val_dir')

In [70]:
len(file_list)

4500

In [74]:
int(file_list[0].split('.')[0])

14147

In [75]:
train[0]

22016

In [76]:
14147 in train

True